### ISSUE TITLE
Mod Suggestion: WAILA

### ISSUE THREAD

**Issue by JRunningZombie** [AlmuraDev/Almura#101]
Waila is an extension for NEI (Not Enough Items) where when you have installed it, a blue box appears at the top of your screen when you are looking at a block or a creature. It shows what it is and what mod it is from. When you open NEI and hover over an item in the grid, it also tells you what mod its from and what it is. I think it would be good for the server as it would help newer players be able to familiarise with the items in different mods by looking at what other players have built and by being able to know what items are from which mod by scrolling through NEI.
Mod review: https://www.youtube.com/watch?v=u2v7S3jz8jQ

http://www.google.co.uk/imgres?imgurl=http://i.ytimg.com/vi/jdX0G0hiBAc/maxresdefault.jpg&imgrefurl=http://www.youtube.com/watch?v%3DjdX0G0hiBAc&h=720&w=1280&tbnid=KT5z83_uijSuFM:&docid=JKh9nkDJIUo5tM&hl=en&ei=nLrhVYTqD-ea7gahh7P4Dw&tbm=isch&ved=0CCkQMygJMAlqFQoTCISoy825zscCFWeN2wodocMM_w

**Comment by mcsnetworks** [comment]
You can add this on your own.
