### ISSUE TITLE
Iron Tinkers tools turn to wood

### ISSUE THREAD

**Issue by Arch112** [AlmuraDev/Almura#103]
I've had sever all iron tools from tinkers construct be turned to wood. It seems to happen when I log out with the item in my backpack. I log in and go to clean my inventory and find that a TC tool that I made from iron is now wood.

Let me know if I can give more/better info to help.

Thanks

**Comment by mcsnetworks** [comment]
This is a known issue.  Don't put items like that in Backpack please.

We are working on a fix to that, its a complicated issue.

**Comment by Arch112** [comment]
Understood.

**Comment by liach** [comment]
Is that an issue with the backpack that could not store the nbt tag of an item stack?
