### ISSUE TITLE
Vanilla Minecraft cauldrons not holding water.

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#104]
The vanilla minecraft cauldron  ( CAULDRON_ITEM - 380:0 ) is 'eating' water you try to put in it from ( WATER_BUCKET - 326:0 ).  

The water bucket 'empties' into the cauldron like it should - but the water just disappears.  It does not show up in the cauldron.  You also cannot pick the water up out the cauldron - so it appears as though the cauldron is eating the water.

This doesn't appear to be a residence issue - as I have tried it outside of a res and gotten the same issue.  Let me know if you need more info.
-Wolf

**Comment by mcsnetworks** [comment]
Make sure you have the bucket flag set T on your residence.  I tested this and its working fine.
