### ISSUE TITLE
Thaumcraft Infusion Altar not accessible after res protect update today

### ISSUE THREAD

**Issue by rcnsol** [AlmuraDev/Almura#105]
Some Thaumcraft blocks/ multiblock structures can not be used after the Residence protection update today. In my case it is the Infusion Altar, which is activated by right clicking the center block (Runic Matrix ID 1500:2) with a wand (Thaumium Bossed Silverwood Wand ID 4966:54), the problem being no reaction. Possibly it is just a flag that needs to be set or if not yet implemented, a flag needs to be created. 

Update: Same issue with the "Seared Faucet" (ID 1724:1) from TinkersConstruct smeltery
(robitect)

**Comment by mcsnetworks** [comment]
This was fixed yesterday.  Wand usage is now tied to the build flag.
