### ISSUE TITLE
Infinite movement speed

### ISSUE THREAD

**Issue by Matterny** [AlmuraDev/Almura#106]
Destabilized redstone on road from minefactory reloaded makes you go way too fast for sanity. (that's why my floor is covered in it). you can store it in buckets with the itemdb of : thermalfoundation_bucket -  5274:0. destabilized redstone is an item made from redstone that emits a redstone signal and flows like water. Road from MFR is a block that makes you go faster. the 2 result in the rough equivalent of speed 255 effect without any effects, this may be used to launch anyone to almost anywhere or load a ton of chunks very fast.

**Comment by mcsnetworks** [comment]
Can't fix this via Almura, will have to wait for a new build of CoFHCore to go along with the newer versions of MFR.
