### ISSUE TITLE
[Question] Is there things like clearlag on the server?

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#107]
I mean whether there's things like "dropped item removal".
I made a Railcraft steam locomotive, and it disappeared when it was an entity on the track after placing it and killing it for few times. I suggest that the locomotive might be removed by plugins like"dropped item removal", since this type of issue had also happened when i was playing other servers.

**Comment by Matterny** [comment]
change it from a question to an issue about the locomotive dissapearing

**Comment by liach** [comment]
You experienced that also?

**Comment by liach** [comment]
Nevermind it should be my client's problem. I found it now.
