### ISSUE TITLE
Skin glitching out after changing worlds

### ISSUE THREAD

**Issue by LeMay23** [AlmuraDev/Almura#108]
Skin: 
![2015-08-30_16 43 43](https://cloud.githubusercontent.com/assets/14045276/9569635/2f1ddb34-4f1d-11e5-9a7e-a4666ecb9c40.png)

Skin Glitch: 
![2015-08-30_16 43 28](https://cloud.githubusercontent.com/assets/14045276/9569639/3a459d08-4f1d-11e5-9d68-788ba931eaaf.png)

**Comment by mcsnetworks** [comment]
This is a known issue.
