### ISSUE TITLE
Sometimes when setting "BackPack" key to none backpack shows when pausing game

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#109]
See title. Also happens to some keys of tinkersconstruct.

Way to reproduce:
1. Set the key
2. Play game and leave the client for a long time
3. This happens.

For the tcon key at first it persists after restarting the game.
For backpack key i pressed esc for more times and it was fixed.

**Comment by mcsnetworks** [comment]
Backpack for Bukkit is being replaced.  Will soon be fixed.
