### ISSUE TITLE
Add the ability for snow biomes to freeze crops

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#11]
If a custom crop is planted in a snow biome or the temperature of the biome changes, it would be nice to have the ability for the crop to freeze and die.

**Comment by Grinch** [comment]
When you say freeze, do you mean stop them from growing or change their texture?
When you say die, do you mean just break as if (for example) there was not enough light?

**Comment by mcsnetworks** [comment]
Our plan, properly implemented would add two types to the growth system.  

Dead:
Frozen:

If a certain condition is met then it the crop in question would change to this state.  Wifee would create additional textures for each plant to achieve the visual representation of this change.

**Comment by mcsnetworks** [comment]
I implemented part of this system.  The crops will now grow in reverse if temperature isn't what is required.  No plans at the moment to kill off a "finished" crop.
