### ISSUE TITLE
Bypassing Claims with Wand Focus: Primial Core

### ISSUE THREAD

**Issue by borderlands121** [AlmuraDev/Almura#110]
I was testing and looking for any thaumcraft items that still work and I happened to find that the wand focus called Primial Core can destroy another players claims. I talked to Wolfeyeamd0 about the issue and the first thing i was told to do was write a report. The items ID is: 
THAUMCRAFT_FOCUSPRIMAL - 4979:0 (WIthout equipped with wand)
THAUMCRAFT_WANDCASTING - 4966:54 (Equipped on wand)

Thank you for your time and all that you do for this server,
                                                                            Borderlands121 (Richie)

**Comment by mcsnetworks** [comment]
Fixed.  But beware, your residence has to be big enough if they fire upon you from the border of your res.
