### ISSUE TITLE
Birch tree sapling growth

### ISSUE THREAD

**Issue by rcnsol** [AlmuraDev/Almura#111]
Item: 6:2 Birch Sapling (minecraft:sapling) 

After planting, when it grows to a tree, the sapling remains as the bottom block of the tree. 

![2015-09-01_00 08 49](https://cloud.githubusercontent.com/assets/9628866/9591805/43a4983c-503e-11e5-89a0-8ff68cf2a211.png)

**Comment by mcsnetworks** [comment]
This is a random bug which I could not re-produce.
