### ISSUE TITLE
Mod Non-Living Entities disappear randomly sometimes

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#112]
Ref #107
As I observed this issue may be temporarily fixed by disconnect and login again. This has been observed on Railcraft steam locomotive and IndustrialCraft2 carbon canoe. In the locomotive case I found it back after login twice, in carbon canoe case I tried to login twice to find it, but it seemes to disappear and I gave up.

Guess: Cauldron's bad handling of special entities? (I do not know about Cauldron server actually, sorry)

**Comment by liach** [comment]
Good point doc. I think it's 99% optifine. Btw Optifine is really a perfect rendering engine...(Without optifine i cannot even see blocks 1 chunk away but entities cause render glitching)

**Comment by mcsnetworks** [comment]
Make sure that you don't have the multi-thread chunk loader on.

**Comment by liach** [comment]
So I guess fastcraft is safe?

**Comment by mcsnetworks** [comment]
If you use fastcraft you run the risk of your entire game going to pieces.

**Comment by liach** [comment]
No! Doc I can confirm it is not a Optifine problem. It is the problem within the modpack.
I downloaded clean b84 today and when I tried to place a minecart on the railroad of the castle, the chest cart disappears.
![2015-09-03_19 52 29](https://cloud.githubusercontent.com/assets/7806504/9675748/a1449ec6-5276-11e5-9020-3562bfc2bf57.png)
In this picture you will see that a part of railroad has been activated by the detector track without any minecart. But you cannot see any minecart which is possible to activate the detector track.
![2015-09-03_19 58 28](https://cloud.githubusercontent.com/assets/7806504/9675764/db156716-5276-11e5-8b2f-04c581b254a4.png)
The minecart found later, the reason of stopping might be that its not in the loaded chunk and the booster track(powered rail) did not receive the redstone signal.

**Comment by mcsnetworks** [comment]
Those minecarts won't force load chunks.  Is that part of the issue?

**Comment by liach** [comment]
Not a chunkloading issue. If it is it should be related to Railcraft anchor cart or something like that.

**Comment by mcsnetworks** [comment]
Please test this bug after we deploy b100.  We could find nothing in our base code that could effect this.

**Comment by liach** [comment]
Ref: http://www.railcraft.info/forum/?mingleforumaction=viewtopic&t=734
