### ISSUE TITLE
Morph and Applied Energistics

### ISSUE THREAD

**Issue by 2veryicey** [AlmuraDev/Almura#115]
I Would Like You To Get The Applied Energistics Mod Because It Adds Tuns Of Cool Stuff, But Most Importantly The ME System! It Allows For Tuns Of Storage, Crafting Automation, ECT! It Also Should Work With The Current Energy Types
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-Separator-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
I  Would Also Like You To Get The Morph Mod Because It Lets You Morph Into Anything That You Kill! 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-Separator-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Get Applied  Energistics Made By : http://ae-mod.info/Downloads/
Get Morph Mod Made By IChunUtil: http://ichun.us/mods/morph/

**Comment by 2veryicey** [comment]
`...

**Comment by Zidane** [comment]
@2veryicey 

Just because you haven't gotten a response doesn't mean we didn't see it. Adding a new mod to the pack is a big undertaking as it has to be evaluated on the grounds of what it does to everyone else's gameplay on the server.

Be patient.

**Comment by gabizou** [comment]
There's already a request for AE2 #85.

**Comment by 2veryicey** [comment]
ok and thanks for answering guys :)

**Comment by mcsnetworks** [comment]
Ae2 has been added, morph is too unstable in a server environment at the moment.
