### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#116]
1. About the usage of eq2online permission system
   I found that it is already included in AlmuraSDK. Is it a check system for litemods?
2. Prevention of Forge `IWorldGenerator` when generating worlds
   Is forge `IWorldGenerator`s disabled in the generation of Faerun? Btw I do not know how do you disable the `IWorldGenerator` in plugin custom world gen.

**Comment by mcsnetworks** [comment]
Faerun is generated using TerrainControl not Forge' world creator.
Not sure what you mean about eq2online perms system.  Please clarify.

**Comment by liach** [comment]
Eq2Online permission system: https://github.com/AlmuraDev/AlmuraSDK/tree/master/src/main/java/net/eq2online/permissions
Implementation: https://github.com/AlmuraDev/AlmuraSDK/tree/master/src/main/java/com/almuradev/almurasdk/permissions

I mean because the Faerun is generated in a way that is never affected by Forge, so I could never find some mod stuff? But some special points like floating islands is also shown on the map like other worlds' new map have. 
![specialspot](https://cloud.githubusercontent.com/assets/7806504/9698223/81dc0e20-5361-11e5-97c9-ba854424b5fd.PNG)

**Comment by mcsnetworks** [comment]
Closing this because now we have implemented this permissions slightly different for b100
