### ISSUE TITLE
"Storeyline" in storyline text

### ISSUE THREAD

**Issue by atenefyr** [AlmuraDev/Almura#121]
I couldn't help but notice this:
![Spelling mistake in Almura.](https://cloud.githubusercontent.com/assets/7481976/9751259/45040fd4-5668-11e5-9455-4c84b1d0c8c5.png)
In the little text that appears every once in the while in the chat while playing Almura, the word "storeyline" is misspelled, instead of the proper "storyline".
While this may not be directly related to Almura's mod, this was the only place I could find to post it.

**Comment by mcsnetworks** [comment]
Fixed.  Ty.
