### ISSUE TITLE
IC2Bridge isn't firing the correct event to block non-player damage to entities

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#122]
If you use a mining laser on an Animal for mob, passive etc the current onLaserHitsEntity event isn't calling the proper forge event for Residence to block this interaction.

**Comment by liach** [comment]
Should it be [this one] (https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/event/entity/living/LivingHurtEvent.java) or [that one] (https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/event/entity/living/LivingAttackEvent.java)?

**Comment by mcsnetworks** [comment]
Have to determine which Forge event fires the Cauldron (Bukkit) EntityAttackEvent

**Comment by mcsnetworks** [comment]
Fixed.  The EntityAttackEvent only fires when player is attacking.  The MiningLaser is its own entity (the laser beam) so it doesn't count in this equation.  Modified ResProtect to catch this as well.
