### ISSUE TITLE
Update to MC 1.8

### ISSUE THREAD

**Issue by Grinch** [AlmuraDev/Almura#125]
Below is a list of mods used by Almura (the modpack). Any checked items are those that are compatible with Minecraft 1.8.

- [ ] [Almura](https://github.com/AlmuraDev/Almura)
- [x] [Applied Energistics 2](https://github.com/AppliedEnergistics/Applied-Energistics-2)
- [ ] [BiblioCraft](http://www.bibliocraftmod.com)
- [x] [Buildcraft](https://github.com/BuildCraft/BuildCraft)
- [ ] [Carpenter's Blocks](https://github.com/Mineshopper/carpentersblocks) << Developer not committed to 1.8+
- [x] [CodeChickenCore](https://github.com/Chicken-Bones/CodeChickenCore)
- [ ] [CoFHCore](https://github.com/CoFH/CoFHCore)
- [x] [CustomMobSpawner](http://mocreatures.org/downloads)
- [x] [Custom NPCs](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278956-custom-npcs)
- [ ] [IndustrialCraft](http://forum.industrial-craft.net)
- [x] [InventoryTweaks](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288184-inventory-tweaks-1-59-march-31)
- [x] [Iron Chests](http://www.curse.com/mc-mods/minecraft/228756-iron-chests)
- [x] [MalisisCore](https://github.com/Ordinastie/MalisisCore)
- [x] [MalisisDoors](https://github.com/Ordinastie/MalisisDoors)
- [x] [Mantle](https://github.com/SlimeKnights/Mantle)
- [ ] [MineFactoryReloaded](https://github.com/skyboy/minefactoryreloaded)
- [x] [Mo Creatures](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272337-mo-creatures-v8-0-0-with-ghost-wyverns-minecraft-1)
- [x] [NotEnoughItems](https://github.com/Chicken-Bones/NotEnoughItems)
- [ ] [Railcraft](http://www.railcraft.info)
- [x] [Tinker's Construct](https://github.com/SlimeKnights/TinkersConstruct)
- [x] [Thaumcraft](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130-thaumcraft-4-2-3-5-updated-2015-2-17)
- [ ] [ThermalDynamics](http://minecraft.curseforge.com/mc-mods/227443-thermal-dynamics)
- [ ] [ThermalExpansion](http://minecraft.curseforge.com/mc-mods/69163-thermalexpansion)
- [ ] [ThermalFoundation](https://github.com/CoFH/ThermalFoundation)

**Comment by mcsnetworks** [comment]
Optifine and ShaderMod is not distributed with Almura.

**Comment by mcsnetworks** [comment]
And your missing CustomNPC's

**Comment by Grinch** [comment]
Updated.

**Comment by Grinch** [comment]
Updated for 1.8 compatibility. Please let me know if there are mods used on the server now that are not listed here. @mcsnetworks

**Comment by gabizou** [comment]
@Grinch btw, https://github.com/CoFH/ThermalFoundation

**Comment by gabizou** [comment]
@Grinch You should likely add AppliedEnergistics to the list. They do have a repo on github as well.

**Comment by liach** [comment]
MineFactoryReloaded: https://github.com/skyboy/minefactoryreloaded

**Comment by Grinch** [comment]
@gabizou and @liach Updated. Thank you.

**Comment by Grinch** [comment]
@mcsnetworks Have any more been added that I should add to this?
