### ISSUE TITLE
b87 to do list

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#127]
1. Update IC2
2. Update Buildcraft
3. Add CustomNPCS

**Comment by liach** [comment]
CustomNPCs might cause laggery, as I've experienced in a GregTech server which become much faster when CustomNPCs got removed.

**Comment by mcsnetworks** [comment]
Depends on how much its used I am sure.

**Comment by mcsnetworks** [comment]
Please until you've got timings data to backup that claim then don't make it.

**Comment by liach** [comment]
Suggestion: Update Mixin Library and MalisisCore (MalisisDoors) since newest MalisisCore(0.12.9 on curse) is conpatible with Mixin `0.4.5-SNAPSHOT` now, reported [here] (https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1761). I've tested also.

**Comment by mcsnetworks** [comment]
You do realize that what we use for mixins is a lot more complex than what Malisis is using right?

If we could do this right now we would have already...
