### ISSUE TITLE
Seed barrel: Soybean glitch

### ISSUE THREAD

**Issue by spinmonk3y** [AlmuraDev/Almura#129]
On attempting to craft a soybean barrel at a worktable (8 soybean seeds in a square around an empty seed barrel, The item will show up in the result preview box, but you will be unable to take it and the components will remain in the table.

Username:omgmonkeysxD

**Comment by spinmonk3y** [comment]
Crafting station*
The preview will not show up on a crafting table, but will still be clickable and the item will appear to be held for a brief second.

**Comment by spinmonk3y** [comment]
Update: this appears to be the case with most to all seed barrels

**Comment by mcsnetworks** [comment]
You aren't suppose to use 8 seeds + an empty barrel.  The recipe is for 64 x 8 stacks + and empty barrel.  NEI doesn't understand multiple quantity recipes.
