### ISSUE TITLE
Immersive Engineering Mod

### ISSUE THREAD

**Issue by Dieheart3** [AlmuraDev/Almura#130]
Immersive Engineering by BlueSunrise and Mr_Hazard.

http://www.curse.com/mc-mods/minecraft/231951-immersive-engineering

I would like to see this mod added because it adds as the name would suggest immersive tech to the game. For instance instead of red pipes for power it has real hanging power lines. There are also many other machines and gadgets that look/feel far more realistic than any others I have seen to date. And as far as I could test it on my private server there were no big errors. A few texture glitches with their animations that are likely fixed by now and that was it. :)

**Comment by mcsnetworks** [comment]
This would need extensive testing because of everything they add.  Also, have you seen whether or not they are working on a 1.8/1.9 build?

**Comment by Dieheart3** [comment]
Yes I know it would need more testing small server test is nothing compared to what has to be tested for a big one. And yes they do have a 1.8 build they are working on but they need to wait for a more stable Thermal Foundation build for 1.8 as they use their Red Flow energy code...

**Comment by liach** [comment]
Note: [Github Page of IE] (https://github.com/BluSunrize/ImmersiveEngineering)

**Comment by mcsnetworks** [comment]
Holding off on this for the moment since we added ae2.
