### ISSUE TITLE
Almura Modded Fence Bug (ID 903)

### ISSUE THREAD

**Issue by Krafko** [AlmuraDev/Almura#134]
Fence from Almura is seen from the side that I place it but not from side that i didnt place it..
![2015-09-20_19 54 46](https://cloud.githubusercontent.com/assets/14374802/9982131/dd9105a0-5fd1-11e5-8c57-249b5e8db777.png)
![2015-09-20_19 54 52](https://cloud.githubusercontent.com/assets/14374802/9982132/df3d53a4-5fd1-11e5-8591-56cb989b993e.png)

**Comment by mcsnetworks** [comment]
This was fixed a while ago.
