### ISSUE TITLE
Industrial TNT

### ISSUE THREAD

**Issue by Dieheart3** [AlmuraDev/Almura#138]
I was clearing out a few of my buildings the fun way by blowing them up with Industrial TNT and found out it bypasses the Res protections when it blew up part of Doc's roadway. Opps :P

**Comment by Dieheart3** [comment]
ok, then... Can also blow other tnt into a protected area where it will explode and break stuff...

**Comment by Dieheart3** [comment]
Inc_BlockITnt 1449

**Comment by mcsnetworks** [comment]
I've added IndustrialCraft TNT to the blacklist until further notice.  They only throw a single event to Forge which is the block break itself and not the explosion event so I have no way to catch the block changes...

**Comment by mcsnetworks** [comment]
@Zidane IC2 throws an event:

ExplosionEvent event = new ExplosionEvent(this.worldObj, this.exploder, this.explosionX, this.explosionY, this.explosionZ, this.power, this.igniter, this.radiationRange, this.maxDistance);

Yet I cannot find a constructor that matches these parameters.

Regardless, this event call isn't calling Bukkit EntityExplodeEvent

**Comment by mcsnetworks** [comment]
We've done as much protection against this as we can.
