### ISSUE TITLE
Railcraft tin plate 5102:2

### ISSUE THREAD

**Issue by Shipka** [AlmuraDev/Almura#140]
The tin plate(5102:2) from railcraft  cannot be crafted.

username;Shipka_

**Comment by liach** [comment]
http://railcraft.info/wiki/part:plate
Check out Rolling machine and give it RF and it will craft items.

**Comment by Shipka** [comment]
I've tried using every form of tin in the rolling machine, I know it's powered because I've been using it to make steel plates, rebar, etc

**Comment by Shipka** [comment]
For whatever reason it's working for me now :/ not sure why it wasn't before...
