### ISSUE TITLE
Lumium Blend Will not work in crafting table

### ISSUE THREAD

**Issue by Dannyboi25** [AlmuraDev/Almura#143]
I and your Mod Wolfe tried it and all but once for her it never worked.
![bandicam 2015-09-29 21-36-19-480](https://cloud.githubusercontent.com/assets/14899818/10183168/4bcd0e02-66f2-11e5-895f-5c7ea421d99d.jpg)
![bandicam 2015-09-29 21-36-38-069](https://cloud.githubusercontent.com/assets/14899818/10183174/53eac408-66f2-11e5-8b87-c349fb415fdf.jpg)
![bandicam 2015-09-29 21-36-42-109](https://cloud.githubusercontent.com/assets/14899818/10183176/56e11c34-66f2-11e5-8518-8396b0fc0fa9.jpg)

My IGN is Dannyboi25

**Comment by Dannyboi25** [comment]
![Uploading bandicam 2015-09-29 21-35-02-575.jpg…]()

my bad i forgot 1 pic of the real recipe

**Comment by liach** [comment]
@Dannyboi25 The pic does not exist, upload it again plz

**Comment by Dannyboi25** [comment]
![bandicam 2015-09-29 21-35-02-575](https://cloud.githubusercontent.com/assets/14899818/10183855/1f8a225a-66fa-11e5-9191-3e2834699f9c.jpg)

**Comment by Dannyboi25** [comment]
Never mind someone else tired it a few hours later and it worked sorry.
