### ISSUE TITLE
update b87c , closed issue #141

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#144]
ok i get this error again have not been able to log in to server for passed 2 days,

**Comment by mcsnetworks** [comment]
Fist,

I need a screenshot of the error.  Did you try to delete the pack and re-add?

**Comment by mcsnetworks** [comment]
I just spoke with Technic again, can you try to login now?  I need a log if it fails.

**Comment by fistidgious** [comment]
yeah i tried delete it thats how i got on last time, this time it kept say that almura was offline and could not download the mod pack. what ever they did fixed it again, if it happens again i make sure to get logs n screen shots up straight away.
