### ISSUE TITLE
Disc Rack access

### ISSUE THREAD

**Issue by Koramin** [AlmuraDev/Almura#146]
Below the "Royal Bedroom" in the new Almura castle, you can access and remove discs from the rack beside the jukebox. Not sure if this was intended or not, but it seemed a bit odd.

X: -1554
Y: 72
Z: -1058

1:48AM
10/2/2015

Koramin

**Comment by mcsnetworks** [comment]
I need a x y z location please.

**Comment by Wolfeyeamd0** [comment]
The itemdb for the item in question is = BIBLIOCRAFT_BIBLIOSTUFFS - 1570:3

**Comment by Dieheart3** [comment]
Didn't you fix this Doc? Why is this still here?

**Comment by Wolfeyeamd0** [comment]
fixed
