### ISSUE TITLE
Stamina level isn't changing evenly with tree fruit breaks.

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#149]
The players stamina level isn't being tracked by the GUI properly.  It will go from completely full to nothing while breaking Fruit tree leaves.

**Comment by Lilai** [comment]
This is also acting "off" in that if you use an axe to "chop" the leaves, you get no stamina/hunger drain at all, and still get leaves.

**Comment by mcsnetworks** [comment]
Fixed in b102.
