### ISSUE TITLE
Assorted issues with update

### ISSUE THREAD

**Issue by Lilai** [AlmuraDev/Almura#151]
NPC Guide Molly isn't working, just says "Hello"

In the Almura Castle sign shop: The tanner sign sells livestock sign instead. The General sign doesn't work for selling the sign. Travel sign isn't there as example and won't sell to you either.

Elfville has/had missing block in path @ -494/133/-207

New trees: Lumberjack mod doesn't chop them from top to bottom, Tinker's lumberaxe doesn't chop multiple blocks/entire tree down. If you use anything except for sheers, breaking the leaves gives you a leaf block instead of going away. Stamina drains at different rates when using sheers to chop leaves, using an axe doesn't drain hunger or stamina all the time. You earn no Lumberjack or Eradicator XP  for chopping or planting trees. Fruit trees however DO give farming XP for planting them and harvesting the fruit from them.

Chopping the new trees with Tinker's Axes doesn't cause degradation on the Axe as used.

Thanks for all the excellent work!!!

**Comment by Lilai** [comment]
Graphic issue on Light Ephedra tree, allowing you to see through certain pixels.
![tree graphic](https://cloud.githubusercontent.com/assets/14955874/10264407/90a185b0-69d8-11e5-8a82-cc5aacb6aae4.jpg)

**Comment by Lilai** [comment]
![missing blocks](https://cloud.githubusercontent.com/assets/14955874/10264445/876145ca-69d9-11e5-9553-55f3fa130ba3.jpg)

**Comment by Lilai** [comment]
Not sure if this is a Carpentry issue or a Shader issue?

![carpbarrierwithhaybale](https://cloud.githubusercontent.com/assets/14955874/10264644/30c816a6-69e0-11e5-865f-c16e47042720.jpg)

**Comment by Wolfeyeamd0** [comment]
Molly, The sign shop (EXCEPT the travel sign), and the block in Elfville have been fixed.

**Comment by Lilai** [comment]
Not sure if this was intentional or not, the new custom trees can not go into the sawmill machine from thermal expansion.

Thanks Wolfe, i can now speak with the illustrious guide Molly :D

**Comment by Lilai** [comment]
Oh! Also the leaves on the new trees do not degenerate on their own, even if the tree has been chopped completely.

**Comment by Wolfeyeamd0** [comment]
Which trees are you having an issue with Lilai?  I know the Fruit ones do degen, sometimes they take longer then others.  I haven't messed with the trees that are not fruit ones though.

**Comment by mcsnetworks** [comment]
Fixed holes in tree image.
Can't fix the fence issue, thats a graphical render issue with Carpenter blocks.
Working on the vines issue.
