### ISSUE TITLE
Server Crash issue with Vanishing frames

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#155]
Krov left this message about the crash during the night of 10/3-10/4.  

I seem to have found another way to crash the server using Vanishing Frames. This time, I attempted to put Afledo Wood Planks in the frame. I could not find anything in the logs to attach so you could see the error.
I do apologize for the inconvenience this causes you, Dockter.

**Comment by mcsnetworks** [comment]
We think we solved this issue.  I would encourage Krov to test on the test server first.
