### ISSUE TITLE
Broken Flowers

### ISSUE THREAD

**Issue by Dieheart3** [AlmuraDev/Almura#156]
Found several Almura custom flowers that cannot be seen from one side, and one that has a weird floaty bit.

Cyprus Bush, Money Tree, Leafy Swamproot, Small Palm, Tall Fern, Rounded Topiary, and Prickly Pear = Invisible from some sides...

Sunnyside = Floaty bit

![2015-10-04_18 09 31](https://cloud.githubusercontent.com/assets/14296517/10270574/bf793324-6ac3-11e5-8a0c-616fa0429964.png)
![2015-10-04_18 09 17](https://cloud.githubusercontent.com/assets/14296517/10270575/bf7afc86-6ac3-11e5-938b-c96d090bdf28.png)
![2015-10-04_18 09 24](https://cloud.githubusercontent.com/assets/14296517/10270573/bf786eb2-6ac3-11e5-99a5-e325a83cf9aa.png)

**Comment by mcsnetworks** [comment]
Fixed in b102
