### ISSUE TITLE
power cables not transferring power correctly

### ISSUE THREAD

**Issue by finitedark** [AlmuraDev/Almura#157]
IC2 cables are not transferring power at the correct rate. ex: generating 200 eu/t, its only transferring 20 - 30 eu/t taking longer time for the power to reach its destination. Tested in single player and found no issue, only in multiplayer. possibly also effecting Thermal Expansion ducts and its rate of transfer as well.

Not sure if its only me who is experiencing it, since no one else seems to have this happen to them.

**Comment by finitedark** [comment]
used a personal anchor and it seems to fix the problem, but that would mean its a chunk load issue and i need a constant supply of enderpearls.

**Comment by Zidane** [comment]
Wires don't transfer power if their chunk unloads. This is by design. Otherwise, you drag the server down as it has to keep simulating those chunks.

@mcsnetworks makes the final call.

**Comment by mcsnetworks** [comment]
The expert @Zidane has spoken and he's right.  My final call isn't warranted.
