### ISSUE TITLE
Bone meal sapling issue

### ISSUE THREAD

**Issue by readalot** [AlmuraDev/Almura#158]
When using bone meal on a sapling the tree grows above the sapling.
The world is atlantis.

All I do is use bone meal on the sapling, it doesn't seem to affect other types of trees.
Bone meal has no affect on spruce saplings (They seem to eat the bone meal), It works properly on the new Light Ephedra sapling.

**Comment by Zidane** [comment]
https://github.com/AlmuraDev/Almura/issues/152

Same issue as above. I'll fix it when time permits.
