### ISSUE TITLE
Quarry always breaks, never drops the item

### ISSUE THREAD

**Issue by rcnsol** [AlmuraDev/Almura#160]
I noticed this happening, ever since the update. First i thought there were stricter rules implemented in the new BC version, but after some testing, it seems it may be a bug, if it is not intended.
Any tool used to break (and pick up for replacing) the buildcraft quarry will break it and not drop the item.
I used different tinkers pickaxes, tried all available wrenches, aswell as the vanilla pickaxe (Iron and Diamond), all give the same result. Even silk touch will not drop the item. 

Item:  BUILDCRAFTBUILDERS_MACHINEBLOCK     1397

(robitect)

**Comment by mcsnetworks** [comment]
This isn't a bug.  We were testing a way to make quarry machines more "expensive", cause they act as giant chunk loaders...

**Comment by rcnsol** [comment]
Ok, almost thought so, but i wasn't sure. Thanks for clearing that up for me.

**Comment by liach** [comment]
@rcnsol Undercutter might help you...
