### ISSUE TITLE
Server Railroad lines

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#165]
Things about railroad:
1. The old railroad going past the castle was removed. Would be good if you can connect them.
2. It would be good for the server to have some railroad lines which require players to buy tickets to use. I suggest to make railroad lines in almura home world for newbie or visitor's sight and views, in celetis/faerun/asgard to benefit players who are travelling. You can make train tickets op-only.
The price should be affordable for those newbies who have $1500.
3. Fix the issue of placing/killing carts in the residence. You should not let player place or kill carts in residences.

Railroad line connection suggestion: 
Celetis: (Build along the land, go past as many residences as possible, prevent go straight above sea(for beauty))
DocksHideOut(Gate in south) - Supergate - DocksCave(DocksFortress)(Gate in north) - SouthFigaro(Gabizou's residence west to dockscave)
Faerun: 
FengZhen (Residence in north) - ChengDu(Two big residences) - Wayward-Home(Gate in east) - DockFind - Supergate - Noobville(Gate in south) - Oddendo( Robitect's residence in far west)

**Comment by liach** [comment]
Btw why did you show your organization of sponge and almuradev doc...

**Comment by mcsnetworks** [comment]
Why not?

**Comment by mcsnetworks** [comment]
You do realize I am members of those organizations right?

**Comment by mcsnetworks** [comment]
This request may be considered.  I've only just begun to cleanup stuff around Almura Castle.

**Comment by liach** [comment]
Yes showing the organization and the new avatar is much cooler. This suggestion will spend a long time and might be difficult to do since I was dreaming for a railroad system in a server... But it seems no server would like to accept this idea.

Btw why are you a collaborator of [sponge-docs-theme] (https://github.com/SpongePowered/sponge_docs_theme) ?

**Comment by Zidane** [comment]
@liach 

Dockter handles the finances of the Sponge project as well as will be a heavy tester once SpongeForge goes primetime.

**Comment by liach** [comment]
Finally the request will be ignored and be an archive right? ~~Though I do not want to see that.~~ It does not matter if you reject this idea, since nearly no server owner/ops would like to spend their time doing this. (btw you cannot place railcraft railroad block with world edit plugin, that will generate some errorous block)
