### ISSUE TITLE
Adding Things Cook Job

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#167]
Cook Job:
Cooked Porkchop
Cooked Fish
Cooked Salmon
Cookie
Steak
Cooked Chicken
Baked Potato
Golden Carrot?*
Pumpkin Pie

All of the custom craft able foods, I can make a list if you want.

In the Cook Job there is both Cake and Cake block - I don't know what the difference is if any, or why both should be in there.

* I stared the Golden Carrot because I'm not sure it should be there.  Both Golden apple and 'speckled melon' are in the Cook Job right now.  I'm not sure what Speckled melon is - might be Glistering Melon.  But, I don't really think these Golden versions of food should be in the Cook Job.  They just seem to not belong.  I don't know where they would go if anywhere.

**Comment by mcsnetworks** [comment]
Ok, so lots of things have been learned.  Jobs was missing the SMELT under cook, I've begun to add this.

Induction Furnaces can't be used with this, Trying to figure out a way to make it so.

**Comment by mcsnetworks** [comment]
Ok, added all of the Almura Food and Drinks to the Cook Job.

**Comment by mcsnetworks** [comment]
Added pumpkin pie and golden carrot.

**Comment by mcsnetworks** [comment]
all cookied fish is just COOKED_FISH with a data value to the item stack.

**Comment by Lilai** [comment]
It also does not register towards Cook if you cook in a Redstone Furnace (Thermal expansion mod).

**Comment by finitedark** [comment]
i made spiced ruby red wine, job lists it as giving 15 xp and 10 gold, i got nothing for making them

**Comment by Lilai** [comment]
Ok, I have gone through crafting all of the "special" foods now. Basically, if it is cooked in a furnace, xp & money is gained. If it is crafted in the crafting table, it does not register anything. This applies to all (I believe) foods and drinks made in the crafting table. I went through the NEI page but page crafting foods/drinks listed, but there is always the chance I missed something.

**Comment by Wolfeyeamd0** [comment]
I'll look into this tonight when I get home.



Sent on the new Sprint Network from my Samsung Galaxy S®4


-------- Original message --------

**Comment by Lilai** [comment]
So we figured it out! Hurray!! The problem is that I was using the Tinker's crafting table. When the vanilla crafting bench is used, XP and money are registered.

**Comment by Wolfeyeamd0** [comment]
I made the Spiced Ruby Wine recipe both ways it is indicated in the NEI and got credit (money and exp) for each of them.  Money does not show up imediatly all the time.  There may be a  second or two lag time in it updating.   

I tested this with making the Wine in question when I no money on me and made only this.

**Comment by Wolfeyeamd0** [comment]
Closing issue.  Everything  seems added for the  most part.  If there are things missing/not working we can start a new issue.
