### ISSUE TITLE
Nei player page access

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#169]
ok i had a few members ask me about item recipies in nei , the lack of and them. when i went to look it up i only had access to page 120 max the play in question`s item was on 123. i tried look it up in creative view and item did not list at all in nei or creative for me " infinite helemet" i asked players on line to see what they could see and a few reported only have pages up to 57 or 96.

ingame Guardian Tb nei page`s 1-120

my nei display is 6 x 16 x 12 pages = 11.520 items
player pausie  is 12 x 17 x 57 pages = 11.628 items

**Comment by Slayer6327** [comment]
ingame name Slayer6327 rank protector nei page 1-127, was looking for infantry helmet, page 123 on my nei when asked tb said he only had page 120,

**Comment by mcsnetworks** [comment]
What happening if you type the name of infinite helmet in the search field, does it appear?

**Comment by Wolfeyeamd0** [comment]
Player: Wolfeyeamd0
Status: Ancient
NEI pages: 1-57

I can see the infantry helmet on page 55 of my NEI.

**Comment by mcsnetworks** [comment]
Any idea what is causing this?  I've got nothing.

**Comment by mcsnetworks** [comment]
No response.

**Comment by Slayer6327** [comment]
i was looking for the infantry helmet not infinite helmet.. im bad with spelling sorry.. 


     On Friday, October 9, 2015 8:48 AM, Dockter <notifications@github.com> wrote:
   

 What happening if you type the name of infinite helmet in the search field, does it appear?—

**Comment by Wolfeyeamd0** [comment]
Okay infantry helmet does it show up?



Sent on the new Sprint Network from my Samsung Galaxy S®4


-------- Original message --------

**Comment by Slayer6327** [comment]
it showed up page 123 on my nei thats what started this, because others were saying theirs went to 90 or lower and some went higher 


     On Monday, October 19, 2015 10:24 AM, Dockter <notifications@github.com> wrote:
   

 No response.—

**Comment by Wolfeyeamd0** [comment]
Finally an answer - How many pages you have depends on how big you display the game.  The smaller the screen/display of the game client - the more pages you have.  The larger the screen/display the fewer pages you have.  So this will be different for different people depending on how they have the game displayed.  All the items are in the NEI regardless however.

**Comment by Slayer6327** [comment]
sorry have been going without internet and been going through family things, sorry for not quickly responding, 


     On Tuesday, November 3, 2015 10:23 PM, Wolfeyeamd0 <notifications@github.com> wrote:
   

 Finally an answer - How many pages you have depends on how big you display the game. The smaller the screen/display of the game client - the more pages you have. The larger the screen/display the fewer pages you have. So this will be different for different people depending on how they have the game displayed. All the items are in the NEI regardless however.—

**Comment by Wolfeyeamd0** [comment]
Not a big deal. It was a silly  simple  answer should have gotten  it sooner.  The important thing is that  all the items are in the Neighborhood regardless of how many pages anyone has



Sent on the new Sprint Network from my Samsung Galaxy S®4


-------- Original message --------
