### ISSUE TITLE
Doku Ornate Stairs

### ISSUE THREAD

**Issue by Lilai** [AlmuraDev/Almura#173]
After switching to the new server, Doku Ornate stairs are destroying when broken rather than being harvested for reuse.

**Comment by mcsnetworks** [comment]
Could not replicate issue.

**Comment by mcsnetworks** [comment]
Bug exists if you don't use a Pickaxe to break a custom stair.  @Zidane

**Comment by Zidane** [comment]
This isn't really a bug since Stairs must be mined with a pickaxe in Vanilla. If its desired to specify otherwise, that is something else altogether.

**Comment by mcsnetworks** [comment]
Incorrect, you can break normal stairs with your hand and it still drops a block, ours isn't.

**Comment by Zidane** [comment]
@mcsnetworks 

You forgot to put a NONE entry into the yml for tools

Remember your hand is a tool in the Pack system much the same as a pickaxe.

**Comment by mcsnetworks** [comment]
This doesn't seem to be an issue anywmore.
