### ISSUE TITLE
igneous extruder not outputting correct amout of obsidian

### ISSUE THREAD

**Issue by finitedark** [AlmuraDev/Almura#175]
Hello,

The Thermal Expansion machine, igneous extruder, is not outputting the correct amount of obsidian when you add upgrades to it. It should be outputting i think 4, 8, and 16 for each upgrade but instead it always output 1.

**Comment by Dieheart3** [comment]
Did you remember to put all the previous upgrades in the machine as well? If you leave the lower ones out the higher ones don't work. Because mine works fine, pumping out 16 a run with no problems at all.

**Comment by finitedark** [comment]
yes i have the upgrades, i can get the increase amount for stone and cobblestone, but not obsidian. Also tested in single player, obsidian only gives 1 no matter the upgrade you put in.

**Comment by mcsnetworks** [comment]
This is a bug with Thermal Expansion by the sounds of it.  Have you checked their forums to see if this was reported?
