### ISSUE TITLE
Almura meat duplication in mod furnaces

### ISSUE THREAD

**Issue by rcnsol** [AlmuraDev/Almura#176]
When you put almura meats in furnaces from mods (ic2, thermal expansion) they duplicate.
Specifically this occurs with
4185:0 - Beef Roast -  ALMURA_INGREDIENTROASTBEEF_RAW
in 
1441:1 - Iron Furnace -  IC2_BLOCKMACHINE
1441:2 - Electric Furnace - IC2_BLOCKMACHINE
1649 - Redstone Furnace - THERMALEXPANSION_MACHINE
results in 2x the amount of
4450 - Roast Beef - ALMURA_FOODROASTBEEF

dont't know if it applies to all meat items, but definitly this one.

(robitect)

**Comment by Wolfeyeamd0** [comment]
This happens with Roast beef in any furnace.  It is meant to be that way.  

Pork Bellies when cooked are also meant to give you 4 bacon per 1 pork belly when cooked.  

No other meats output a different amount then what goes in.

Thank you for reporting, but not a bug.
