### ISSUE TITLE
Custom NPC guns

### ISSUE THREAD

**Issue by Lilai** [AlmuraDev/Almura#177]
Guns will still fire and do damage within No PVP zones.

**Comment by mcsnetworks** [comment]
Your not suppose to be even getting those.

**Comment by Dieheart3** [comment]
There are recipes to craft them by default.
To get rid of said recipes go into the edit page of a npc and go to the last tab. Look for the recipe creation sub-tab and remove them...

**Comment by Wolfeyeamd0** [comment]
The recipes are now removed from the list of NPC recipes.  Now we just need to figure out what to do with the ones that already exist.

**Comment by mcsnetworks** [comment]
I'm going to close this an hope this goes away on its own.
