### ISSUE TITLE
Is Spout dead?

### ISSUE THREAD

**Issue by dretax** [AlmuraDev/Almura#178]
Is spout dead? I was looking at the site, but It seems to be down. I wanted to go and update my plugins to It. =(

**Comment by mcsnetworks** [comment]
Yes, quite dead. 

SpongeForge is what is replacing it essentially from a server perspective:

https://github.com/SpongePowered/

**Comment by dretax** [comment]
Is the API the same?

**Comment by Zidane** [comment]
@dretax 

While there are similarities, its vastly different. SpongeAPI is a Minecraft API, not a generic game engine API like Spout was.

**Comment by dretax** [comment]
Any way to find all the old released plugins that were on the spout forum?

**Comment by mcsnetworks** [comment]
I may be able to dig it up from an archive.  Anything your looking specifically?

**Comment by dretax** [comment]
well if you could send all it would be great

**Comment by mcsnetworks** [comment]
That I can't do which is why I asked for specifics.
