### ISSUE TITLE
Zombies from vanilla spawner does not give exp when killed

### ISSUE THREAD

**Issue by finitedark** [AlmuraDev/Almura#179]
Hello, Zombies that are spawned from the vanilla zombie spawner does not give xp or money for hunter job when killed

**Comment by Wolfeyeamd0** [comment]
The zombies spawned in the wild appear to give exp/money.  This was also tested with a Skeleton Spawner to see if it was related to all the spawners - however the Skeletons spawned from the Skeleton Spawner did give money/exp.  So this appears to just be an issue with the Zombie spawner.

**Comment by fistidgious** [comment]
this has been the case on here for a long time even back in spout days spawners did not give xp. i believe its to stop grinding spwaners for xp ant make it earned by actualy playing and fighting mobs properly. (Tb -Tunnel_brat)

**Comment by liach** [comment]
I wonder that does zombies from mob spawner tile entity drop vanilla exp orb and its ordinary drops?

**Comment by Wolfeyeamd0** [comment]
Okay - Note I said that the Skeletons from a spawner were working with the hunter job though.

I know that the Skeletons from a spawner drop exp orbs and it's normal drops - it's one good way to farm bones for bonemeal.  Zombies from a spawner also drop their normal drops and exp orbs.

Note this is all about vanilla spawners - not about any weird new spawner thing.

**Comment by mcsnetworks** [comment]
Will need to figure out why event.getSpawnReason() isn't returning SPAWNER for those mobs that are actually giving out xp and money as they shouldn't be.

**Comment by mcsnetworks** [comment]
JobsPaymentListener tags entities with a metaData flag that isn't set if the mob is spawned via spawner.

**Comment by mcsnetworks** [comment]
Residence is going this as it detects the player having moved the spawner.
