### ISSUE TITLE
Requesting ore dictionary mod to interchange ingots of different types 

### ISSUE THREAD

**Issue by finitedark** [AlmuraDev/Almura#182]
Hello, can we get ore dictionary mod so that ingots of the same metal but different type can be interchangeable on the crafting table rather than re-smelting it?

example, i have tinker construct tin ingot which i can use crafting table to turn into IC2 tin ingot, which i can turn into thermal expansion tin ingot, and repeat. Rather than having to macerate tin ingot then re-smelt for IC2 ingot, or pulverise then smelt.

**Comment by mcsnetworks** [comment]
What mod?

**Comment by finitedark** [comment]
lexicon does the job
