### ISSUE TITLE
World borders

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#183]
hi i see council members r given ability to go passed the world borders r guardians get this to as i have been pushed back on all world boarders in the list

kind regards TB

**Comment by Dieheart3** [comment]
Council members should be able to go past it but, on Othala at least we cannot even though it is on Doc's list of worlds we should be able to...

**Comment by mcsnetworks** [comment]
Fixed for both of you.  I have to enable this per person.
