### ISSUE TITLE
2 nether worlds ??

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#184]
hi doc i logged into dynamap today as usual decided to go get some soul sand from the nether, when i used the portal in my old primus base in dakara it took me to my usual spot in the nether, i had the dynamap set to follow me and it didnt change to Natu/nether. i tried to get to that world but it jus dont seem to happen, i never showed on the map that i`m in there. So i am wondering has the server created 2 nethers like it is doing with the false end world ?

regards fist/Tb

**Comment by fistidgious** [comment]
hi player LeiderLivolt used his own portal to go to the nether today and did not show on dynamap natu/nether, his icon was grayed out as tho he was in another world but could not be tracked, and he

**Comment by liach** [comment]
It seems natu/nether had once existed on dynmap even before b100 big refactor.
