### ISSUE TITLE
Things to add to container 

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#186]
BIBLIOCRAFT_BIBLIODESK 
BIBLIOCRAFT_BIBLIOTHECA
BIBLIOCRAFT_BIBLIOWORKBENCH

Each one of these has Acacia, Oak, Spruce, Dark Oak, Birch, jungle and framed types 

BIBLIOCRAFT_TILEBIBLIOFRAMEDESK

This is a standalone no other types like it.

**Comment by Wolfeyeamd0** [comment]
Also looks like you fixed that Disk rack issue - so you can close that ticket

**Comment by mcsnetworks** [comment]
Done.
