### ISSUE TITLE
Walnut/Peach tree bugs

### ISSUE THREAD

**Issue by Dieheart3** [AlmuraDev/Almura#187]
These two trees will not grow in my base's biome. 
Their leaves also break and don't drop the leaf block itself even with shears. 
None of the others have given me these problems.

**Comment by Wolfeyeamd0** [comment]
What is your base's biome? have you tried bonemealing them?

**Comment by Dieheart3** [comment]
Bonemealing yes I have. Wasted 4 stacks, and waited 3 RL days, nothing won't grow. Even with clear skys and clear space for 20x20x20 around them. ;/ Biome is Plains it says, but It is a custom Othala biome so donno.

**Comment by Wolfeyeamd0** [comment]
I want to take a look at these tonight because I had no issues with mine when I grew them - but I grew them in a desert.

**Comment by mcsnetworks** [comment]
What type of block are you planting the tree on, BE VERY SPECIFIC

**Comment by Dieheart3** [comment]
Dirt, Grass, and Podzol. Tried several different things at my base... In Dakara it was Grass...
