### ISSUE TITLE
Barbed wire no texture from back

### ISSUE THREAD

**Issue by Arch112** [AlmuraDev/Almura#189]
Barbwire in the customs shop has no texture from the back. It is located at X: -1330 Y: 72 Z: -1260.
Thank you

**Comment by Dieheart3** [comment]
Ahh snother person brings this up and it still isn't fixed? Well I suppose the other was on the forum and not here. Hmm...

**Comment by Wolfeyeamd0** [comment]
This is a different item then the one I saw on the forums.  

Barbedwire itemdb - ALMURA_DECORATIONCEP_BATTLECRAFTWW2_BARBWIRE - 975:0

**Comment by mcsnetworks** [comment]
Was fixed a while ago apparently.
