### ISSUE TITLE
Help Guide problem

### ISSUE THREAD

**Issue by deadoss** [AlmuraDev/Almura#191]
I have noticed that when you hit escape to exit the guide, it tells you to read the membership and rules guides. The guide named Membership does not exist. It should say to read the Citizenship Page. Alot of new players have taken this to mean that they should read the outdated Status Level page. 

The part that is outdated is:

Status Level Details: Visitor
(Left out the unimportant bit)
"You must first build a basic house in order and request a Moderator or Admin to come and inspect your house in order to be promoted to Member".

It should tell them to visit each city.

**Comment by Wolfeyeamd0** [comment]
Fixed the Visitor part of the Status Level guide.  Should make more sense.
