### ISSUE TITLE
Feature suggestion: Voice over

### ISSUE THREAD

**Issue by deadoss** [AlmuraDev/Almura#192]
Hi, I have no idea if this is even possible. but is there anyway we can have a voice over play when someone first joins? It would give a quicker way to citizenship and the guide would still be used for more indepth information.

It could go over the most important parts of the guide.

Such as:
Basic Rules
Citizenship

If it is possible, I would be more than willing to do the voice work for you.

**Comment by Wolfeyeamd0** [comment]
Have you seen the NPC's in the Visitor spawn?  Also - What happens if, like me, they keep sound off for the game?

**Comment by deadoss** [comment]
Fair point, Might i suggest that we clean up the info guide then? Some of its info is outdated and it could use some general organization.
