### ISSUE TITLE
Make Thermal Expansion strongboxes and caches work with chest shops

### ISSUE THREAD

**Issue by ryanaddams** [AlmuraDev/Almura#193]
Specifically items Strongbox [1654:1], Hardened Strongbox [1654:2], Reinforced Strongbox [1654:3], and Resonant Strongbox [1654:4]

Also make Thermal Expansion caches work if possible, specifically items Cache [1655:1], Hardened Cache [1655:2], Reinforced Cache [1655:3], and Resonant Cache [1655:4]

**Comment by aqwdude3** [comment]
If you really want these to work,you can put a itemduct connecting the cache/strongbox to a chest and having the said itemduct using a servo to extract the item into said chest,your welcome :)

**Comment by mcsnetworks** [comment]
Added to signshop configuration.  Be careful when your setting up the caches with a sign.
