### ISSUE TITLE
Blocks to add to the Builders Job

### ISSUE THREAD

**Issue by zdaysavior** [AlmuraDev/Almura#194]
The following is a list of the Item IDs of blocks that I would like to have added to the Builders Job list:

RAILCRAFT_BRICKABYSSAL - 1550:2

ALMURA_BUILDINGBRICKS_BLOCK_B_SUPERSMOOTH - 510:0

CARPENTERSBLOCKS_BLOCKCARPENTERSBLOCK - 1769:0

CARPENTERSBLOCKS_BLOCKSGARAGEDOOR - 1775:0

CARPENTERSBLOCKS_BLOCKCARPENTERSSLOPE - 1765:0

CARPENTERSBLOCKS_BLOCKCARPENTERSCOLLAPSIBLEBLOCK - 1776:0

ALMURA_BUILDINGBRICKS_BLOCKS_B_CSBRICK1 - 497:0

ALMURA:BUILDINGBRICKS_BLOCKS_B_SBRICK1 - 502:0

This is just a quick list, and there may be more requested to be added at a later date, though not many, if i'm thinking of the blocks correctly

**Comment by mcsnetworks** [comment]
@zdaysavior 

Please check the following:

[08:43:40] [Server thread/WARN]: [Jobs] Job Builder has an invalid Place type property: ALMURA:BUILDINGBRICKS_BLOCKS_B_SBRICK1!
[08:43:40] [Server thread/WARN]: [Jobs] Job Builder has an invalid Place type property: ALMURA_BUILDINGBRICKS_BLOCKS_B_CSBRICK1!
[08:43:40] [Server thread/WARN]: [Jobs] Job Builder has an invalid Place type property: CARPENTERSBLOCKS_BLOCKSGARAGEDOOR!

I suspect you messed up the name.

**Comment by zdaysavior** [comment]
So, I reviewed the three that are listed, and it was all simple typos, adding an extra letter to the ID:

CARPENTERSBLOCKS_BLOCKGARAGEDOOR - 1775:0

ALMURA_BUILDINGBRICKS_BLOCK_B_CSBRICK1 - 497:0

ALMURA_BUILDINGBRICKS_BLOCK_B_SBRICK1 - 502:0

**Comment by mcsnetworks** [comment]
Fixed.  Thank you.
