### ISSUE TITLE
Scythe not giving money for all 9 blocks...

### ISSUE THREAD

**Issue by Dieheart3** [AlmuraDev/Almura#196]
Ok so with the farming job you can harvest crops to get money.
The scythe lets you harvest a 3x3 area.
But you only get money from the farming job for the center block you click on.
Was told you fixed the hammer, could you fix this one too please?

**Comment by mcsnetworks** [comment]
I can't actually fix this due to how we listen to the block break events and how we detect it within Almura break listener.
