### ISSUE TITLE
We Need To Go Deeper

### ISSUE THREAD

**Issue by Omazing** [AlmuraDev/Almura#198]
When I use flint and steel on a portal I can't get the achievment; I have gotten the DIAMONDS!! Achieve. Showed Lighting the portal infront of Wolfe no succes and no thoughts on it.

**Comment by fistidgious** [comment]
are you lighting portal in main world dakara ??

**Comment by Omazing** [comment]
Yes, I've tried in Celestis and Darka for the achievement

**Comment by Omazing** [comment]
had to enter the nether after lighting the portal We Need To Go Deeper +1 Achieve
