### ISSUE TITLE
Thermal Dynamics - ItemDucts reconnectioning

### ISSUE THREAD

**Issue by Omazing** [AlmuraDev/Almura#199]
I have removed the facades and pipes replaces them swapped out caches however it reconnects when I reload.

**Comment by Omazing** [comment]
It seems to be anytime te pipes reload they reconnect to everything they were connecting to before going to test leaving the pipes out and waiting a day.

**Comment by Omazing** [comment]
Nothing has been working would love somebody too see this github issue. or have some one say something so I feel like my issue isnt ignored.

**Comment by liach** [comment]
Does it reconnect in single player game?

**Comment by Omazing** [comment]
No it seems to be a specific set of pipe/block spaces that they will reconnect. One by my front door and six behind my caches, I've even used the wrench.

**Comment by mcsnetworks** [comment]
What happens if you try and put a world anchor in the area to do this?
