### ISSUE TITLE
Almura 3.0 - New food / recipe Suggestions

### ISSUE THREAD

**Issue by Lilai** [AlmuraDev/Almura#202]
Granted I don't know what foods are already in the making, and we already have a lot of great foods possible. However, based on the ingredients we already have, I thought of a few more recipe possibilities.

Chicken/Beef PotPie
Chicken/Beef (possibly ground?)
Chicken Broth/Beef Broth
Salt
Pepper
Carrot
Peas
Ball of Dough

Candies!!!!
Strawberry/Blueberry/Blackberry/Cranberry/Orange/Grape/Bannana/Pineapple/YummyBerry/Mint
Sugar
Gelatin

IceCream
Milk
Snow
Salt
Vanilla Bean/Cocoa Bean/Strawberry/Mint

Guacamole (I mean how do we have avocado and no guac?)
Ground Avocado
Salt
Pepper
Mayonnaise
Lemon

Summer Sandwich
Slice of Bread (2)
Avocado
Tomato
Mayonnaise
Salt
Pepper

Can't wait to see what else is created!!!

**Comment by Dockter** [comment]
Moved to resources.
