### ISSUE TITLE
Charcoal blocks.

### ISSUE THREAD

**Issue by gtakingg** [AlmuraDev/Almura#203]
I was going to make some charcoal blocks as I was tired of filling my generator up with normal charcoal. When I went to craft them it didn't work but Wifee told me that a 3x3 square of 64 is what you actually need. When I came to put my charcoal block in my generator, expecting it to have the same burn time as 9 stacks of charcoal, but all I got was 2 seconds at the most...

Please fix...

Item ID) 673

**Comment by mcsnetworks** [comment]
Yes and no.

Charcoal block is a special recipe, required 64 x 9 stacks to make 1 charcoal block.  What you did was create a broken block which the server detected as bad and killed it off early.  Some how you bugged it to create what you did.
