### ISSUE TITLE
Fish 349 Salmon 349:1 - Undetected by: Hardened Retrievers ; Fish 349 Undected by: Hardened Servos

### ISSUE THREAD

**Issue by Omazing** [AlmuraDev/Almura#205]
I have everything Correctly set up Hardened Retriever/Servo redstone sign - Disabled, Impulse itemducts (opaue) connected to chests and whitelisted rottenflish, Salmon and Fish.

**Comment by mcsnetworks** [comment]
Please contact the mod dev for Hardened Servos.  We have no control over this code.
