### ISSUE TITLE
Mod suggestion - ExtraTic

### ISSUE THREAD

**Issue by DekofAlmura** [AlmuraDev/Almura#207]
ExtraTic; I personally enjoy that it adds more tool options using mods like thermal expansion which can have a good effect of a persons experience on a server; Primary owner: Glassmaker. Direct link:http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445212-extratic-tinkers-construct-mod-support-add-on

**Comment by DekofAlmura** [comment]
As of now, Glassmaker is looking to update to 1.8

**Comment by aqwdude3** [comment]
I support this mod request as i have looked at and experienced the mod in many modpacks,and have found it to be fun and immersive,I highly reccomend it as a addition to almura

**Comment by deadoss** [comment]
I support this suggestion as it will tie some of our mods together, making the whole experience more enjoyable. Also more weapon variety!

**Comment by mcsnetworks** [comment]
Will be testing this weekend.

**Comment by mcsnetworks** [comment]
Deemed to be damaging to the current environment during testing.  Will not be included.

**Comment by mcsnetworks** [comment]
@Deadoss, during testing this seemed to open up a real nightmare for Residence.  PM me when you have time about this please.

**Comment by DekofAlmura** [comment]
[Extra Tic Chart.xlsx](https://github.com/AlmuraDev/Almura/files/72845/Extra.Tic.Chart.xlsx)

**Comment by mcsnetworks** [comment]
This is currently outside of the intended narrative of Almura Origins.
