### ISSUE TITLE
Backpack items lost on death or server restart

### ISSUE THREAD

**Issue by jermangarc** [AlmuraDev/Almura#209]
I left my character logged in last night to go do a quick chore, but I moved all inventory items to my backpack, in case I died I would not lose them. When I returned the server had closed. I figured there was an update so I went to bed. i logged back in today to find my backpack empty. Not sure if I died or was it because of the restart? - CAP10Zeus

**Comment by mcsnetworks** [comment]
Next time please make sure you logout. Backpacks only save when the backpack closes.  The scheduled server restart has been in place for 3+ years and its been announcing it every time its done.
