### ISSUE TITLE
Adding Things Cook Job 2

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#211]
crafting these items gives no experience or money
Ham shanks 
Ham slices 
K-7 BBQ Sauce
Chunk of cheese
Ground pork
Ground beef
Sausages
Ground chicken
Soda water

*These were all found when I was making items to craft more food.

**Comment by Wolfeyeamd0** [comment]
Mayonaise as well

**Comment by Wolfeyeamd0** [comment]
flour too

**Comment by Wolfeyeamd0** [comment]
Syrup as well

**Comment by Wolfeyeamd0** [comment]
Coconut milk

**Comment by Wolfeyeamd0** [comment]
Noodles
Vegtable oil
red pasta sauce
White pasta sauce
Oil and Herb mix

**Comment by Wolfeyeamd0** [comment]
Dough - I had so much made before the changes to cooking that I didn't realize it wasn't paying until I made more

**Comment by mcsnetworks** [comment]
Wolf, I need the actual itemdb's of these items.

Place the item in your hand then type /itemdb

**Comment by Wolfeyeamd0** [comment]
Ham shanks  -  ALMURA_INGREDIENTSHAMSHANK - 4154:0
Ham slices  - ALMURA_FOODHAMSLICE - 4398:0
K-7 BBQ Sauce - ALMURA_INGREDIENTSBARBECUESAUCE - 4119:0
Chunk of cheese - ALMURA_FOODCHEESE - 4368:0
Ground pork - ALMURA_INGREDIENTSGROUNDPORK - 4153:0
Ground beef - ALMURA_INGREDIENTSGROUNDBEEF - 4151:0
Sausages  - ALMURA_FOODSAUSAGE -4478:0
Ground chicken - ALMURA_INGREDIENTSGROUNDCHICKEN - 4152:0
Soda water - ALMURA_INGREDIENTSMATERIALS_SODAWATER - 4168:0
Mayonaise - ALMURA_INGREDIENTSMAYONAISE - 4170:0
flour - ALMURA_INGREDIENTSFLOUR - 4147:0
Syrup - ALMURA_INGREDIENTSSYRUP - 4195:0
Coconut milk - ALMURA_FOODCOCONUTMILK - 4373:0
Noodles - ALMURA_INGREDIENTSNOODLES - 4172:0
Vegetable oil - ALMURA_INGREDIENTSVGETABLEOIL - 4199:0
red pasta sauce - ALMURA_INGREDIENTSPASTA_REDSAUCE - 4178:0
White pasta sauce - ALMURA_INGREDIENTSPASTA_WHITESAUCE - 4179:0
Oil and Herb mix -  ALMURA_INGREDIENTSOILANDHERBMIX - 4175:0
Dough - ALMURA_INGREDIENTSDOUGH - 4146:0

**Comment by Dockter** [comment]
Will add these in 3.0.
