### ISSUE TITLE
Add SolarFlux

### ISSUE THREAD

**Issue by rcnsol** [AlmuraDev/Almura#215]
I would like to suggest a fairly simple mod, since there is no means of high tier RF production other than ungodly amounts of dynamos/turbines. It is basically an equivalent to CompactSolars, just for RF Production. I could not determine if the creator intends to create a 1.8/1.9 version. 
I tested it with Almura in Singleplayer mode; everything worked as expected, no conflicts or crashes. 
It would also decrease server load tremendously, as only a few can cover high power needs.

Full mod name: Solar Flux
Primary developer: Nauktis

https://github.com/Nauktis/SolarFlux

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2187592-solar-flux-a-k-a-compactsolars-for-redstone-flux

**Comment by Lilai** [comment]
This is the best "possible" solution we've found as well. Robitect and I tested in single player also, very slick. I like that it has scaleable teirs. The end teir is still pretty costly, but with it's output you don't need nearly as many, so overall much more resource friendly to the server. 
One other link: http://minecraft.curseforge.com/projects/solar-flux

**Comment by mcsnetworks** [comment]
This will be tested this weekend.

**Comment by mcsnetworks** [comment]
This is currently outside of the intended narrative of Almura Origins.
