### ISSUE TITLE
Mod Suggestion: Forge Multipart 1.7.10

### ISSUE THREAD

**Issue by Blakeroni155** [AlmuraDev/Almura#216]
I suggest adding Forge Multipart because while we have a fair bit of decorations, there are no recipes for most. this mod adds the ability to craft a flint/iron/diamond saw which then can be either crafted below or next to any full vanilla/modded block in a crafting table, and gives you different sizes and shapes such as posts, pillars, strips, nooks, corners, covers, slabs, and panels. these smaller blocks can all be placed into the size of one block, also allows multiple torches/redstone torches/levers/and buttons to be placed in one block, and still be separately functional.
Developer: Chicken_Bones
Minecraft Forums Page: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods
Versions download:http://files.minecraftforge.net/ForgeMultipart/
Mod Spotlight (In case you want to see exactly what it does.): https://www.youtube.com/watch?v=u9yUr4jmU6s

**Comment by mcsnetworks** [comment]
I'm not going to lie, this would be absolute hell to get Residence to work with.  I would prefer to wait until Almura 3.0 before adding this ability.
