### ISSUE TITLE
Add Chisel 2

### ISSUE THREAD

**Issue by Blakeroni155** [AlmuraDev/Almura#217]
This time i am suggesting the Chisel 2 mod. Its yet another awesome decoration mod that lets you craft a iron/diamond/obsidian chisel which you right click to open a gui that allows you to change vanilla block textures to 10-12 different preset textures. Alternatively, you can continuously left click a chisel-able block to cycle through the different textures.
Original Dev: AUTOMATIC_MAIDEN
Current Dev: TheCricket26
Minecraft Forums page: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2254671-chisel-2-2-5-1
Download page: http://www.curse.com/mc-mods/minecraft/225236-chisel-2/2256718

**Comment by mcsnetworks** [comment]
As I haven't tested this yet I will I have a question.  Is it a tool that is used to change the texture of the block?

**Comment by Blakeroni155** [comment]
Yes, its a tool  that changes the texture of most blocks, even torches, to other textures that are preset in the files of chisel 2

**Comment by mcsnetworks** [comment]
This is now outside the plan for Almura.
