### ISSUE TITLE
Cannot start/download Almura

### ISSUE THREAD

**Issue by hazarufus** [AlmuraDev/Almura#220]
I get the following error:
-----------------------------------------------------------------------------------
Error unzipping a file for the following pack: Almura

Attempting to extract file almura-1.0.zip, but it did not exist.

Please consult modpack author.
-----------------------------------------------------------------------------------
I have tried uninstalling the pack and reinstalling it, and have also tried deleting all the almura files and reinstalling and nothing has worked also before i uninstalled the pack to reinstall its said it needed to update then i got the above error.
    -Thanks for listening

**Comment by mcsnetworks** [comment]
Please make sure you have the pack set to "Recommended Build".
