### ISSUE TITLE
Thaumic Energistics

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#224]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2150151-1-7-10-tc4-ae2-thaumic-energistics

**Comment by cdsimpson3465** [comment]
Closing 226 as  duplicate of this issue

Integration between AE2 and Thaumcraft
http://minecraft.curseforge.com/projects/thaumic-energistics

**Comment by mcsnetworks** [comment]
To be included.
