### ISSUE TITLE
Bug: Inventory unnamed item causes crash on login.

### ISSUE THREAD

**Issue by Blakeroni155** [AlmuraDev/Almura#228]
I have not been able to login since  2 days ago when a weird block randomly appeared in my inventory. It is named "unnamed"  and is a black colored block in either my first or second hotbar slot. I am asking that it be removed from my inventory! thanks!

**Comment by Zidane** [comment]
@Dockter will look into this when he has tonight.

**Comment by mcsnetworks** [comment]
Try and login.  If the change I made didnt work I'll have to wipe your player file to fix the issue.

**Comment by Blakeroni155** [comment]
Thanks i can login now :D It worked perfectly!
