### ISSUE TITLE
Mod Suggestions!

### ISSUE THREAD

**Issue by SwiftFlux** [AlmuraDev/Almura#230]
Schematica

Dev:
Lunatrius

About:
With this mod you're able to display a ghost image of a schematic file inside Minecraft to rebuild a structure or export any part of your world (or a server's world) into a schematic file. You're able to export parts of your world, too!

What I Like/Need:
I have builds in creative that I would like to build on Almura easily.

OpenBlocks

Dev:
Not Sure

About:
OpenBlocks introduces a range of random ideas into Minecraft. There is no theme. Some of it is rather silly! Requires OpenModsLib 0.9.

What I Like/Need:
The Hang Glider

Download Links:
OpenBlocks: https://openmods.info/downloads/OpenBlocks-1.7.10-1.5.jar
OpenModsLib: https://openmods.info/downloads/OpenModsLib-1.7.10-0.9.jar
Schematica: http://curse.com/project/225603

**Comment by liach** [comment]
I think the server already got some sort of plugins which could export parts of the world, even other softwares can do so. OpenBlock should be pretty good. [(Link to the description)](https://github.com/OpenMods/OpenBlocks#what-does-it-contain)

**Comment by infiswifr** [comment]
I meant SinglePlayer to MultiPlayer.

**Comment by mcsnetworks** [comment]
This is currently ouside the intended scope of Almura 2.5+
