### ISSUE TITLE
Add QuiverBow

### ISSUE THREAD

**Issue by SpartanofEarth** [AlmuraDev/Almura#235]
QuiverBow is an interesting mod by Domochevesky that adds in several different types of ranged weapons, ranging from crossbows to a handgun that converts a mob into a spawning-egg of that mob(which is quite expensive, I might add.) When I've used it before on modpacks similar too this one, it seemed to interact well with other mods, and didn't eat up very many system resources. The mod can be found here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292078-quiverbow-ranged-weaponry-thought-up-by-steve

**Comment by Wolfeyeamd0** [comment]
Just going to note that we do have crossbows from tinker's construct on the server.  I don't think they do anything fancy like turn anything into a spawn egg of the creature.  There were handguns on the server but they had to be removed due to ignore residence perms.

**Comment by SpartanofEarth** [comment]
Hmmm... yeah, the server I was on didn't have the residence plugin, so I can't be sure how it would interact with it without testing that first. Either way, I was simply suggesting it because it seemed interesting, and wasn't aware of the tinker's construct crossbows. I guess I'll just mess around with those for now.

**Comment by Wolfeyeamd0** [comment]
Apologies, my post wasn't meant as a 'No don't do this'  It was meant to make sure when this is looked by Dock and the others that they know what is currently around.

**Comment by mcsnetworks** [comment]
This plugin is currently outside of the planned narrative for Almura Origins and beyond.
