### ISSUE TITLE
Permission to reset Thaumcraft Data for infiswift

### ISSUE THREAD

**Issue by SwiftFlux** [AlmuraDev/Almura#237]
so i want to start over with thaum, so i want allll my data reset. I have a couple threads on how to do it

http://forum.feed-the-beast.com/threads/resetting-thaumcraft-research.7037/

http://thaumcraft-4.wikia.com/wiki/Commands

**Comment by mcsnetworks** [comment]
Thaumcraft was removed from Almura so this is no longer applicable.
