### ISSUE TITLE
Ars magica 2 and other Popular Mods [Mod suggestion]

### ISSUE THREAD

**Issue by Gullgum** [AlmuraDev/Almura#238]
I think we should have more magic in this pack, we already have Thaumcraft, why stop there?
Ars magica is very popular so I'm sure it will update to 1.8  and 1.9 in the future. I'm sure it wont have any problems with Sponge, the only thing I'm not sure about are the ores it adds.
More Thaumcraft addons like Automagy and Thaumic Tinkerer would be nice too.
Please try and add these. ;)

Or maybe at least Botania and Witchery, they don't add much worldgen.
Also Chisel 2 would be amazing, lots more block patterns to use while building.

**Comment by mcsnetworks** [comment]
This suggestion is currently outside of the narrative planned for Almura Origins and 3.0
