### ISSUE TITLE
New Moderator commands

### ISSUE THREAD

**Issue by deadoss** [AlmuraDev/Almura#239]
During the escapades of last night, I've noticed alot of people asking questions which are easily answered with the guide. Therefore I suggest that we need a new command that moderators and above can type that will cause the info guide to open for specific players.

Perhaps the command could be like this 

/openguide (playername)   
You might even be able to have it open to a specific page.
For example   /openguide (playername) (pagename)

Also, with our recent catching of a thief, I have come to realize that if it happens again and no admin is online, moderators do not have to tools to deal with that sort of thing. 

So my suggestion: Allow mods access to the prism logs for breaking, and placement stuff, if possible you can even remove the rollback options, Just need the logs.

**Comment by mcsnetworks** [comment]
Not possible before Almura 3.0.
