### ISSUE TITLE
Broken Custom items

### ISSUE THREAD

**Issue by deadoss** [AlmuraDev/Almura#240]
I went through the customshop to find all the broken textures that I can find. 

Faction Flag ID 1153
The reverse side of the block shows the flag attached to the flagpole wrong. 
the texture appears normal on the front, but backwards on the reverse.

Training Dummy ID 1217
Texture is just plain broken, it appears that half of the texture is see through

Empty Rack ID 439
The texture for the rack is see through at some angles.

**Comment by mcsnetworks** [comment]
These issues cannot be fixed with our current model editor.  We have already fixed these in 3.0.
