### ISSUE TITLE
Add to Container Perm for Residence

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#243]
Barrels- CUSTOMNPCS_NPCBARREL - 1818:0
              CUSTOMNPCS_NPCBARREL - 1818:2
              CUSTOMNPCS_NPCBARREL - 1818:3
              CUSTOMNPCS_NPCBARREL - 1818:4
              CUSTOMNPCS_NPCBARREL - 1818:1
              CUSTOMNPCS_NPCBARREL - 1818:5

Crates - CUSTOMNPCS_NPCCRATE - 1813:0
              CUSTOMNPCS_NPCCRATE - 1813:1
              CUSTOMNPCS_NPCCRATE - 1813:2
              CUSTOMNPCS_NPCCRATE - 1813:3
              CUSTOMNPCS_NPCCRATE - 1813:4
              CUSTOMNPCS_NPCCRATE - 1813:5

Weapon Racks- CUSTOMNPCS_NPCWEAPONRACK - 1810:0
                          CUSTOMNPCS_NPCWEAPONRACK - 1810:1
                          CUSTOMNPCS_NPCWEAPONRACK - 1810:2
                          CUSTOMNPCS_NPCWEAPONRACK - 1810:3
                          CUSTOMNPCS_NPCWEAPONRACK - 1810:4
                          CUSTOMNPCS_NPCWEAPONRACK - 1810:5

Pedistals - CUSTOMNPCS_NPCPEDISTAL - 1804:0
                  CUSTOMNPCS_NPCPEDISTAL - 1804:1
                  CUSTOMNPCS_NPCPEDISTAL - 1804:2
                  CUSTOMNPCS_NPCPEDISTAL - 1804:3
                  CUSTOMNPCS_NPCPEDISTAL - 1804:4

**Comment by mcsnetworks** [comment]
Done.
