### ISSUE TITLE
Item issues: Res

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#244]
Someone used Alumentum to break part of the Citiadel (they reported it to me and I fixed it)  But i clearly isn't being picked up in Residence flags somewhere.

Alumentum - Thaumcraft_itemResource - 4983:0

Another item is 'Wrench' there are several other wrenches but this one allows people to break certain machines and pipping (not all) and take them from a res.

Wrench - Buildcraftcore_wrenchitem- 4578:0

**Comment by mcsnetworks** [comment]
Thaumcraft and Buildcraft were removed from Almura so this is no longer applicable.
