### ISSUE TITLE
Almura Preferred Font 2?

### ISSUE THREAD

**Issue by SwiftFlux** [AlmuraDev/Almura#245]
So I made a font and i think it goes very well with the Almura Modpack. If you took the time to reveiw it please send feedback.

Download Link(Its safe): http://www.mediafire.com/download/saszn0brhmgxb7v/Almura_Preffered_Font_2.zip

Thanks,
infiswift

**Comment by Grinch** [comment]
While I appreciate the time you put in to this, I have to say I don't think it fits the feel of Almura. Granted, neither do the GUI windows.

The biggest issue with this font in my eyes is it's a bit.. flashy I guess is the word I'm looking for. 

@mcsnetworks Looking for feedback from you as well.

**Comment by mcsnetworks** [comment]
@Grinch being your the GUI guy, I take your recommendation without question.
