### ISSUE TITLE
Thaumcraft Magic Mirror Issue

### ISSUE THREAD

**Issue by huma42** [AlmuraDev/Almura#246]
Finally got my Thaumcraft up enough to make some magic mirrors.  Also made some Travelers gear to send to my wife.  Throw the chest, boots, and goggles through the mirror and they never made it through.  I'm not sure if it was because of the enchantments or not as we've sent lots of mundane items through.  Either way this will be the last time we send armor through.

My in game name is huma39.  I reported it to ~Wolfe and he did a quick check for any known issues but didn't find anything and suggested I put it up here on the github.  The armor had all been upgraded with autorepair and the tinkers construct upgrades.

If you need any more info let me know and I'll be glad to help out in any way possible.  I would love to get the armor back at least.

Thanks

**Comment by huma42** [comment]
After playing with it a bit more, the problem seems to be repeatable with tinkers construct items like an iron shovel created with TC.

**Comment by mcsnetworks** [comment]
No longer an issue as Thaumcraft was removed.
