### ISSUE TITLE
safari net launcher not working properly

### ISSUE THREAD

**Issue by staticbear76** [AlmuraDev/Almura#248]
hi this is staticbear76 I have noticed this issue yesterday after I caught a dolphin and rescued it form almost beaching itself at a mesa the safari net launcher has not launched since keeps going into release mod constantly and not firing right it shows the nets being gone then reappearing a minute later empty in the inventory started around 7 pm feb 12th 2016 please help be mostly gratiously appreciated..

**Comment by mcsnetworks** [comment]
Mod removed so this is no longer applicable.
