### ISSUE TITLE
A mod suggestion

### ISSUE THREAD

**Issue by ChickenChaser99** [AlmuraDev/Almura#249]
I like the mod Compact Machines it allows you to create a single block that inside of it is varying sizes of rooms to set up your machine (A big reactor would be a perfect use for this mod) that you could then attach lines to the inside and then the corresponding outside to run an entire reactor out of a single block

Link to the mod: http://www.curse.com/mc-mods/minecraft/224218-compact-machines
Dev: Davenonymous
Sponge/1.8-1.9: There wasn't any place saying they were but I did leave a message for the dev asking if they had plans for it.

**Comment by ChickenChaser99** [comment]
Got a reply from someone on their team they do have plans to upgrade to 1.8

**Comment by mcsnetworks** [comment]
At the moment this is outside of the narrative of what we want Almura 2.5 and 3.0 to be.
