### ISSUE TITLE
cook job

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#250]
hi i joined the cooking job tried a few recipes "orange soda" and receive`d no money or xp ,only had a bit of luck cooking vanilla recipe eg potato an chicken , i am an elder in game not sure if it may be a member lvl status as i was told a few other peeps could not craft the orange soda, i can make the drink and its components but receive no rewards. i left job and rejoined to see if it was a log in issue with it but all was the same.

 kind regards fistidgious

**Comment by Wolfeyeamd0** [comment]
I currently have a ticket running with all the things that don't currently give out money: Adding things to Cook Job 2.  I just tied to make Orange soda and it worked perfectly for me - Money and XP wise.  

The one thing to note with crafting things is that Cooking only recognizes when you make the individual thing.  So if you try to make a stack of Orange soda with Shift +Click method it will only recognize 1 was made - you currently have to single click them.  

Soda water does not give out money or xp and is noted in the ticket I have running.

I didn't join cooking until we updated it to include a bunch of the custom foods and was already Admin level.  And I know there were two people who leveled up to 100 cook with orange soda alone, they were Protectors.  

With cooking things in furnaces I believe there are some furnaces that just don't work right with cooking - but I know the vanilla one works fine.

Any other questions please let me know
~Wolfe

**Comment by mcsnetworks** [comment]
Won't be resolved in 2.0.
