### ISSUE TITLE
Mod request to make lives easier! 

### ISSUE THREAD

**Issue by Blackdogsniper** [AlmuraDev/Almura#251]
PowerCoverters, this mod will allow you to craft items that will let you convert power sources to other power sources (rf, eu, generic steam, ic2 steam) with no limitations. These have internal conversion rates that are pre set (Eg 1eu = 4rf). Currently the only way to convert rf to eu and back is with 1 set of rednet energy cables which can only do up to 2000rf/t which is very little when compared to most high energy draw or generating items (such as nuclear reactors). 
Here is a link to the page http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293983-powerconverters-originally-by-powercrystals
I've tested build 72 with our pack in single player and didn't see any issues. I couldn't get build 75 to work (would crash on startup)

**Comment by mcsnetworks** [comment]
This won't happen as we've started Almura 3.0 and begun pealing off mods.

**Comment by Blackdogsniper** [comment]
Thanks for looking at it though doc, how is 3.0 coming along?
On Apr 27, 2016 7:44 AM, "Dockter" <notifications@github.com> wrote:

This won't happen as we've started Almura 3.0 and begun pealing off mods.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/AlmuraDev/Almura/issues/251#issuecomment-215106383>
