### ISSUE TITLE
I changed my name and my thaum data was reset

### ISSUE THREAD

**Issue by SwiftFlux** [AlmuraDev/Almura#252]
http://thaumcraft-4.wikia.com/wiki/Commands 

I had all research, i would like to have it back please.

New Name: Infinitive
Old Name: infiswift

**Comment by Wolfeyeamd0** [comment]
I am not comfortable using that command when I don't really have anyway of Verifying what your progress was.

**Comment by mcsnetworks** [comment]
Not an issue we'll fix under 1.7.10
