### ISSUE TITLE
What happened to almura?

### ISSUE THREAD

**Issue by TBUnivese** [AlmuraDev/Almura#254]
I was playing on almura and crashed saying I had a bad value packet and now everything is down, I cant get on almura or even the map.

**Comment by liach** [comment]
reinstall modpack?

**Comment by TBUnivese** [comment]
dosent work, it says Internal Exception: io.netty.handler.codec.DecoderExeption:java.io,EOFException

and in my technic launcher console it says its caused by java.io.IOException: Bad packet id 1284009

**Comment by TBUnivese** [comment]
I think it may be an item in my inventory but, I don't want to clear it because I was moving and have literally all of my items on me in my ME drives

**Comment by TBUnivese** [comment]
if an official can please clear my inventory I would be most grateful as I am almost certain it is an item I am holding, thank you

**Comment by liach** [comment]
@Zidane Could you help? You are currently the most active member of Almura on GitHub,

**Comment by mcsnetworks** [comment]
Tb, I seen that you had been logged on within the last 2 hrs, is this still an issue?

**Comment by liach** [comment]
I should not ping Zidane, sorry.

**Comment by TBUnivese** [comment]
yes, I can log in but I get immediately kicked

**Comment by TBUnivese** [comment]
sorry to be impatient but, I started a megabuild on almura and I don't want to leave it un-res'd so could you clear my inventory so I can get into the server and continue playing on almura

**Comment by mcsnetworks** [comment]
Resolved.
