### ISSUE TITLE
Almura 3.0 - Status and Issues thread

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#258]
Below is a known list of things that are preventing Almura 3.0's development and release.

@Zidane, @Gregabyte , @Grinch please add to this list as needed.

- Permissions system has to be tweaked.  Current PermissionsEx hasn't been properly configured for groups.
- Need to figure out a way to protect server area's using Grief Protection.
- Need to figure out a way to do Shops, with Broker Plugin will / should replace it.

The following MODS are not ready for 1.10.2 or above
- Backpack

**Comment by coolnickname** [comment]
InventoryTweaks updated to 1.10.2: http://inventory-tweaks.readthedocs.io/en/latest/#download

**Comment by mcsnetworks** [comment]
Updated: 3.9.2017

**Comment by liach** [comment]
?

**Comment by mcsnetworks** [comment]
Closed because it is continued on a newer thread.
