### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by TBUnivese** [AlmuraDev/Almura#259]
Hello, i reccomend adding the mod "Chisels & Bits". this mod allows you to make custom decorations by placing or chiseling out blocks. this mod is very low lag and has versions for 1.7.10 up to 1.10. this mod will give people the ability to make decorations with limitless possibility. Ex: http://imgur.com/a/pP0sx   

- here is a link to their GitHub page: https://github.com/AlgorithmX2/Chisels-and-Bits/graphs/contributors 

- Minecraft forum page: https://github.com/AlgorithmX2/Chisels-and-Bits/graphs/contributors 

- Download page: https://minecraft.curseforge.com/projects/chisels-bits

**Comment by mcsnetworks** [comment]
With Almura Origins, we are trying to stay close to the original Almura 1.0 narrative. This recommendation is outside of what would be considered for our pack.

**Comment by liach** [comment]
Sad...
