### ISSUE TITLE
[Mod suggestion] Furnus

### ISSUE THREAD

**Issue by rcnsol** [AlmuraDev/Almura#261]
Hi,
not meaning to jump the gun here, but I would like to recommend this mod: Furnus. Very simple, it adds a grinder and a furnace. They are both upgradeable for speed, fuel efficiency, etc. 
Versions exist for 1.7.10 through 1.10.2, i have extensively tested it on a 1.10.2 server as well.
It would be a wonderful addition IMO, since vanilla furnaces are a drag.

- Github: https://github.com/MrRiegel/Furnus
- Curse: https://minecraft.curseforge.com/projects/furnus

**Comment by mcsnetworks** [comment]
Hello,  we already have this ability using "AutoFurnace".  Check out the display setup in Almura Castle to see an example setup.
