### ISSUE TITLE
Add Items to Assembly Line Furnace

### ISSUE THREAD

**Issue by rcnsol** [AlmuraDev/Almura#263]
Hi,

while it works fine for most ores and food, i came across a few that are ignored by the AssemblyLineFurnace plugin.

Here a list:
ALMURA_ORESMARBLEORE - 974:0
ALMURA_INGREDIENTSPORKBELLY_RAW - 4183:0

REDSTONE_ORE - 73:0
DIAMONED_ORE - 56:0
LAPIS_ORE - 21:0
COAL_ORE - 16:0

This is by no means complete, this is what i could test so far.

**Comment by mcsnetworks** [comment]
I'll add these later this evening.  Thanks for reporting.

**Comment by mcsnetworks** [comment]
Added.  I'll update the server the next time I have it down for maintenance.
