### ISSUE TITLE
Able to put fires out in Almura Castle.

### ISSUE THREAD

**Issue by Dannyboi25** [AlmuraDev/Almura#264]
Today I went to Almura Castle and was able to left click on the fires at the pillars at the donator spawn and 
put them out completely.

**Comment by Wolfeyeamd0** [comment]
Are we talking actual fires?  Because if so I don't think it's fixable to fix it.  If you 'hit' the fire it will be put out.

**Comment by mcsnetworks** [comment]
BlockFire doesn't throw a blockDamage event when you put it out, as stupid as that is.

@Zidane can you make sure Sponge does this.
