### ISSUE TITLE
Jobs Miner Addition

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#266]
Can we add Sandstone to the Miner Job?

**Comment by Blackdogsniper** [comment]
Abyssal Stone 1532:6

**Comment by liach** [comment]
@Blackdogsniper And the dark ore from Railcraft.

**Comment by Wolfeyeamd0** [comment]
Poach please list the thing you want added, vague descriptions Don't help when Dock goes to add these to the job.

Get Outlook for Android<https://aka.ms/ghei36>



On Sun, Sep 18, 2016 at 9:36 PM -0500, "liach" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Blackdogsniper<https://github.com/Blackdogsniper> And the dark ore from Railcraft.

-

**Comment by mcsnetworks** [comment]
Fixed.
