### ISSUE TITLE
Stone ax regening durability glitch

### ISSUE THREAD

**Issue by finitedark** [AlmuraDev/Almura#267]
I had two stone axes, one broke, the other one im currently using keeps regening its durability. its goes to orange or red then turns back to green with like 80% durability. has happened multiple times and wont break.

**Comment by Wolfeyeamd0** [comment]
The axe appeared to break as well - and then re spawned in inventory with durability in the green again.

**Comment by mcsnetworks** [comment]
I haven't been able to reproduce. 

Please provide world and location you were in when this happened.  be exact.
