### ISSUE TITLE
AutoFurnace feed chest list needs updating

### ISSUE THREAD

**Issue by Blackdogsniper** [AlmuraDev/Almura#269]
Stone
Raw Porkbelly
Raw Turkey
Raw Ostrich
Raw Rat
Egg

**Comment by liach** [comment]
Why doesn't it just check from `FurnaceRecipes` class?

**Comment by mcsnetworks** [comment]
You Don't cook stone...

**Comment by Blackdogsniper** [comment]
If you put stone into a furnace it makes super smooth stone. Not exactly cooking but the furnace does process it

**Comment by mcsnetworks** [comment]
Fixed.  I will update server at the next down time.
