### ISSUE TITLE
Demonic Staff/ Staff enchant

### ISSUE THREAD

**Issue by zdaysavior** [AlmuraDev/Almura#272]
The above staff mentioned is just a specific example, but the staves are able to get an enchant that allows for use without mana, will abstain from mentioning which so people don't try to get it as well. Showed Wolfe the staff and tested it with an unenchanted version of the same staff and nothing happened with the plain one.

**Comment by Dockter** [comment]
No longer an issue since the mod which was creating the conflict is no longer being used.
