### ISSUE TITLE
Seed Barrels - Recipe error

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#274]
The bamboo shoot seed barrel uses 7 full stacks and 1 single seed from the 8th stack to craft the barrel so you end up with 63 leftover from the 8th stack in your craft table.

When you place the barrel and break it though - it spits out 8 full stacks of seeds.  Really easy way to cheat for more bamboo shoot seeds.

**Comment by deadoss** [comment]
Just Fixed the issue, Updated recipe is being pushed to the 2.0 content packs.

**Comment by mcsnetworks** [comment]
Fixed.
