### ISSUE TITLE
Grass and Wheat Bales.

### ISSUE THREAD

**Issue by Omazing** [AlmuraDev/Almura#275]
Grass Bales - Breaking Error - 8 Wheat and 1 String given back.
Wheat Bales - Duplication Error - 4 Bales - 8 Wheat 1 String - Breaking one will cause 8 Wheat and 1 String to drop.

**Comment by deadoss** [comment]
Made the grass bales drop grass, and changed the amount crafted to 1 to prevent a duplication problem. 
Did the same to prevent a wheat duplication problem.

**Comment by mcsnetworks** [comment]
Fixed.
