### ISSUE TITLE
Cache issues.

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#281]
Issues:

- Since the Cache is only a single slot, devices such as hopper have an issue making stacks larger than 64 because no only does it check the stack size in the cache but the stack in the hopper against Item.

- TileEntity sometimes gets lost, reverts to default level of 64.  Haven't been able to find cause.

**Comment by Zidane** [comment]
Logic has been changed to left click withdrawal, right click deposit. When it gets emptied, it does clear the cache.

Rendered stack is now fixed to only show a quantity of 1.
