### ISSUE TITLE
Farm Crops not growing in 9x9 squares.

### ISSUE THREAD

**Issue by brbkidinoven** [AlmuraDev/Almura#285]
Found out why crops don't grow in Square sections. in a 9x9 Area the center crop is staying at stage 0. Due to no water, etc. Crops around it x4 spaces (9x9) will not grow past stage 1. Tested this by bone mealing center stage 0 crop to Stage 1. Other crops in area immediately started growing to Stage 2. I would assume with works at other stages as well. I do not know if this is a feature to get fields to grow evenly or not. I do not know why having one crop not grow would hinder another 80 crops. I can replicate this on request.

**Comment by mcsnetworks** [comment]
This is by design.  The stage growth pattern is dependent on the others around it.  This prevents a field from having a stage 5 plant in the same field and close to a stage 1.
