### ISSUE TITLE
Random Crashing, past 4 crash logs.

### ISSUE THREAD

**Issue by brbkidinoven** [AlmuraDev/Almura#287]
[crash-2016-11-01_01.17.46-client.txt](https://github.com/AlmuraDev/Almura/files/572305/crash-2016-11-01_01.17.46-client.txt)
[crash-2016-11-02_12.19.00-client.txt](https://github.com/AlmuraDev/Almura/files/572306/crash-2016-11-02_12.19.00-client.txt)
[crash-2016-11-04_11.10.00-client.txt](https://github.com/AlmuraDev/Almura/files/572307/crash-2016-11-04_11.10.00-client.txt)
[crash-2016-11-04_12.29.07-client.txt](https://github.com/AlmuraDev/Almura/files/572308/crash-2016-11-04_12.29.07-client.txt)

**Comment by brbkidinoven** [comment]
Dead wanted me to post them since i had 2 close together.

**Comment by mcsnetworks** [comment]
Two of these was from the stupid sound bug that mojang still hasnt' fixed after 4 years, the other two have been fixed.
