### ISSUE TITLE
Bucket Stacking bug

### ISSUE THREAD

**Issue by finitedark** [AlmuraDev/Almura#289]
When you stack buckets holding a liquid and use it on a block, it destroys all buckets but 1 and you lose the liquids as well.

example i have 16 water buckets use on a tile, it places the water and im left with 1 empty bucket losing everything else.

**Comment by finitedark** [comment]
Now we have  a bug with tinker's construct smeltery. If you use a stack of lava buckets to add fuel to it you lose a bucket.

example: i have 16 lava buckets, i add to smeltery, smeltery gets the lava but i only have 15 lava buckets and no empty bucket. the empty bucket disappears.

**Comment by mcsnetworks** [comment]
I can't fix the tinkerers issue.
