### ISSUE TITLE
Gui Bug

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#293]
hi doc/devs a new player has had an issue with the gui depend on its settings auto,large,normal,small he could not see the almura custom crops.

i decided to look at it by change my gui scale from auto to normal to see if it affected me, all seemed well till i tp`d back to my base area when the game kicked me off. i tried relog again it kept kick me off, i reinstalled pack totaly but that did not fix it , eventualy i put a single player world on and set gui back to auto and tried to relog back on server wher it let me on.

**Comment by mcsnetworks** [comment]
I could not replicate.
