### ISSUE TITLE
TC Rapiers

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#294]
It looks like the TC Rapiers are blacklisted but I can't figure out why - they seem to fallow the res rules and do not ignore diamond or nano armor.

Do we remember or know why they are blacklisted?

The NPC one is black listed as well - but that one DOES ignore things.

**Comment by deadoss** [comment]
If memory serves, they got blacklisted because they used to ignore all armor. Perhaps they were updated.

**Comment by Wolfeyeamd0** [comment]
That's what I thought but I tested  it on someone in a res with PvP off and it didn't damage.  Maybe some further testing is required? Can look into it more tonight.

Regardless it isn't listed in our blacklist.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Dec 13, 2016 at 8:54 AM -0600, "deadoss" <notifications@github.com<mailto:notifications@github.com>> wrote:


If memory serves, they got blacklisted because they used to ignore all armor. Perhaps they were updated.

-

**Comment by deadoss** [comment]
interesting, I would look into it further, but I'm currently in Portugal. :P

**Comment by Wolfeyeamd0** [comment]
I'll mess around more tonight.  I only had like 10 min after raid last night before I went to bed.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Dec 13, 2016 at 9:14 AM -0600, "deadoss" <notifications@github.com<mailto:notifications@github.com>> wrote:


interesting, I would look into it further, but I'm currently in Portugal. :P

-

**Comment by Wolfeyeamd0** [comment]
Okay so tested it out outside of a res and it does punch through armor somewhat - but doesn't deal it's full damage.  

This is the thing that explains it:  http://ftb.gamepedia.com/Rapier

As far as I can tell it's working as intended and isn't doing anything it shouldn't.  It's just a really nasty weapon because of what it is intended to do.
