### ISSUE TITLE
Railcraft Railroad in Public Domain

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#295]
Different from Almura 2, Almura 2.5 has a separate world-Asgard. Asgard is a public domain. In comparison to #165, now the cleanup is complete. Can the railroad system be done now?

> It would be good for the server to have some railroad lines which require players to buy tickets to use. I suggest making railroad lines in almura home world for newbies or visitor's sight and views, in Celetis/Faerun/Asgard to benefit players who are traveling. You can make train tickets op-only.
The price should be affordable for those newbies who have $1500.
Fix the issue of placing/killing minecarts in the residence. You should not let player place or kill carts in residences.

This time, railroads will only be in Asgard. But this is still an issue:
- [ ] Fix the issue of placing/killing minecarts AlmuraDev/ResProtect#3

 in the residence. You should not let player place or kill carts in residences.

This time, I drew several maps for my railroad plans.

Each color denotes a line. Blue stars are railway stations.
Asgard Railroad:
![Asgard Railroad](https://cloud.githubusercontent.com/assets/7806504/21171839/4d7db890-c183-11e6-8866-0acc0fe596f9.png)

In Almura Castle, the railroads should be built like light rails or subways. The distance between stations is way shorter.
Almura Castle Railroad:
![Almura Castle Railroad](https://cloud.githubusercontent.com/assets/7806504/21171838/4d7d97de-c183-11e6-94e6-b1875748649b.png)

Railcraft also has a type of cosmetic item called emblems. There are several emblem codes. Some of them are symbols and signs. I have a [list](https://gist.github.com/liach/23f3d955451a5881633a4031981c686d) of publicly available emblems.

**Comment by deadoss** [comment]
I have a few comments on this. 

1. The railroad will not be able to be made of High speed rails, Since a mob on the tracks can destroy it.
2. As i see it, the current way we weed out undesirable players is partly by using the distance between towns as a test for patience, and commitment, if we had a rail system, it would be very simple to just complete the quest.

**Comment by liach** [comment]
1. We can use reinforced tracks or electric tracks.
2. We can limit major railroad in islands to citens or peasants, and open subways to visitors.

**Comment by liach** [comment]
Orilla, a newly created world under server protection, is also a good place for railroads. I suggest to build it in mineshaft style.

**Comment by Wolfeyeamd0** [comment]
I was planing on replaceing most of the oak walkway with those road blocks that speed up walking

That will make it a bit faster

**Comment by liach** [comment]
Railroad plan for Orilla done:
![Orilla railroad](https://cloud.githubusercontent.com/assets/7806504/21212538/77452d9c-c242-11e6-832c-e650637047c5.png)

**Comment by mcsnetworks** [comment]
I am not apposed to this idea.  Actually think its a good one.

**Comment by Wolfeyeamd0** [comment]
All I know is it won't be me making as I have no idea how that stuff works.  I did lay down the road blocks that speed up walking on the main path between cities, left the bridges dock modified

Get Outlook for Android<https://aka.ms/ghei36>



On Sun, Dec 25, 2016 at 10:39 AM -0600, "Dockter" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not apposed to this idea. Actually think its a good one.

**Comment by mcsnetworks** [comment]
I would like to start working on this but I need RC 1.12.x.

**Comment by Dockter** [comment]
Liach, we can start working on this once RC 1.12.2 arrives.....

**Comment by liach** [comment]
Yeah, I agree. Railcraft is too dead now; covertjaguar has been hunting.

**Comment by Dockter** [comment]
Wasn't the 1.12 branch almost done?  Is he the only one with commit access?

**Comment by liach** [comment]
He does not allow me to commit directly to protected branches, yeah. And only he can release (but both he and I are "very busy" now because of hunting and school)
