### ISSUE TITLE
Issues with items

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#296]
The fallowing items ignore Residence perms and allow people to interact and take things from them

NPC items:

All 5 of the-

CUSTOMNPCS_NPCPEDESTAL 

McCray's:

CFM_ITEMMICROWAVE - 6361:0
CFM_ITEMBLINDS - 6422:0
CFM_ITEMPRINTER - 6365:0
CFM_ITEMKITCHENCABINET - 6383:0
CFM_ITEMCAVINET - 6384:0
CFM_ITEMWALLCABINET - 6389:0
CFM_ITEMOVEN - 6273:0
CFM_ITEMDISHWASHER - 6286:0
CFM_ITEMBEDSIDECABINET - 6292:0
CFM _ITEMBIN - 6344:0
CFM_TEMWASHINGMACHINE - 6350:0
CFM_ITEMFRIDGE - 6353:0

**Comment by Dockter** [comment]
Will be resolved in Almura 3.0
