### ISSUE TITLE
Almura Broker - Idea's and implementation.

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#299]
Basically want to implement Everquest 2's Broker system in Minecraft.

![image](https://cloud.githubusercontent.com/assets/1034770/21472119/1085b468-ca90-11e6-917a-d0e7f9df01c4.png)

**Comment by mcsnetworks** [comment]
Key features:
- Players would have the ability to list as many items as they have space for.   You would put a container in the one of the 6 slots.
- Players would have access to only one slot to begin with and would earn / purchase more spots.
- Players would be able to set prices per item and chose to list / delist items at will.
- Players would use an NPC to open this broker window, no commands.
- Players would be able to search for items from other players by item name, player name etc.
- Note:  Things not needed from this window:  ANY of the presets, item effect, special, class, tier, slot or special.

**Comment by Grinch** [comment]
An attempt at this would need to start with @Zidane working on the backend since that is where his talents are.

**Comment by Grinch** [comment]
Going to ask a few questions now that I'm close to tackling this.

> Players would have the ability to list as many items as they have space for. You would put a container in the one of the 6 slots.
Do you want to keep the container system or can we make this a single-item-per-slot system?

> Players would have access to only one slot to begin with and would earn / purchase more spots.
If we can make this a single-item-per-slot system we can give you something like 6 slots to work with at the start and let you increase it to 10 or more via various methods in-game.

> Players would be able to set prices per item and chose to list / delist items at will.
We discussed this a bit but I want to further discuss this. Do you want this entirely a player controlled market or do you want to have guiding prices that give an idea of what the average market value is at the current time? Reason I ask is to help avoid price manipulation.

> Players would be able to search for items from other players by item name, player name etc.
The way I'll handle this will likely end up being similar to how you search GitHub issues. Something along the lines of `seller:"Ninja Grinch" item:"minecraft:dirt"` which would search for Dirt sold by Ninja Grinch. This may change as I design the GUI more and get a feel for how I can make this a bit more convenient.

> Tax system
I believe a hard 10% tax on all transactions should be applied. My goal is to break down the transaction details before someone actually buys or sells something.

> Ability to sell items directly to the broker at a set price. Volume of which the server can buy would be determined on what the "master" account has in it from taxes.
Is this meant to be an item sink (eat items to remove them from the server)? If we follow a market value as I mention earlier we can make it so you get 25% or 50% from the Broker of the current market value (not a lot I know but we want to encourage actually selling the item, if you sell to a broker you're basically acknowledging you want a quick sale for less cash)

> A person with the appropriate permissions would be able to set the servers price.
I feel the server should only have an introductory price that is used upon first being added to the game (initial release of Broker, new items in future updates). From then on we can follow the market price on how it goes.

> Could prices for crops be a commodity price? As it would go up or down based on how much is being dumped onto the market?
This would follow the market price I mention earlier.

I really want to push for a market price that acts as a guide so to speak. It's easier to combat price manipulation if we make it so the market value can't go up or down by more than X% a day and have the server calculate new market prices at a set point in the day.

That's my two cents and questions regarding this so far.

**Comment by Grinch** [comment]
I've received enough input on this to begin work on the project. Am closing this issue now.
