### ISSUE TITLE
Mechanic Idea: Companion Crops

### ISSUE THREAD

**Issue by deadoss** [AlmuraDev/Almura#303]
In the real world certain crops are beneficial to the growth rates of other crops. this is known as a companion crop. 

we could implement a system to check which crop type is in a 3x3 radius and either speed up the growth rate, or slow it down based on which crops are in the area. It would need to still allow a field of the same crop to have default growth rate.

This could create a system that encourages variety in farming, and would increase the efficiency of farming.

**Comment by mcsnetworks** [comment]
How would we account for the edge of the field?  Example:  In a corn field the edge of the field still typically grows at the same rate as the rest of the field.

**Comment by deadoss** [comment]
Perhaps we could assign values to each block/crop and do some math to determine if the growth rate should speed up or slow down.

Another potential option would be to tie the system into our almanac system. this would allow crops to improve or diminish the soil quality. which would encourage players to do proper crop cycles. other than that, i'm not certain.

**Comment by Dockter** [comment]
Added to Almura 3.0 - Release 4.
