### ISSUE TITLE
Almura 3.0 - Restore Crops functionality

### ISSUE THREAD

**Issue by Zidane** [AlmuraDev/Almura#316]
This will need to be a specific stage as Crops have attributes that neither Blocks nor Horizontals have.

**NOTE**: age = crop stage

This will happen in multiple parts:

- [x] Devise new format for Crops pack files
- [x] Generate new crop pack files
- [x] Separate seeds into their own pack files
- [x] Generate OBJ files for Crop stages
- [x] Generate blockstates with age variants
- [x] Add builders for Crops/Crops stage
- [x] Add Crops specific loading stage to loader
- [x] Add Stage tasks
 - [x] Add crop/crop stage core attributes task
 - [x] Add set seed task

**Comment by Dockter** [comment]
This has been completed.
