### ISSUE TITLE
Integration with discord

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#319]
Discord is a chatting platform that can easily integrate with IRC or Minecraft servers. It can record the chat log, allowing users not to always be idle like on IRC. It supports transferring chats between Minecraft and Discord servers with the assistance of mods or plugins. One example of server-side-only mod supporting multiple Minecraft versions ranging from 1.7.10 to 1.11 is here: https://github.com/shadowfacts/DiscordChat
Although Discord has voice servers, you can disable them by deleting voice channels. Here is a comparison between TeamSpeak and Discord in voice:
http://forum.teamspeak.com/threads/122871-Benefits-over-Discord-compared-to-TeamSpeak

**Comment by liach** [comment]
@kashike See this. We talked on sponge discord already.

**Comment by Grinch** [comment]
This is a low priority for Almura at this time. We'll revisit this when some other priority things have been completed.
