### ISSUE TITLE
CustomNPCs weapon dealing damage in residence

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#320]
![2017-01-11_16 56 17](https://cloud.githubusercontent.com/assets/7806504/21873114/33922542-d821-11e6-8a7f-7092f14798b5.png)
![2017-01-11_16 56 18](https://cloud.githubusercontent.com/assets/7806504/21873113/3391a16c-d821-11e6-864a-3d4f9e4d60d1.png)

I with player Bai_Sugar was playing on the server, and we found that the wand from Custom NPC mod can deal damage in the residence. It is some sort of wand, the exact name is forgotten; but all of that type of wand can deal damage. Discovered by player Bai_Sugar.

**Comment by mcsnetworks** [comment]
Fixed.
