### ISSUE TITLE
Inquisitor item status display misorganized

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#321]
Inquisitor displays inventory status in a buggy format.
Reproduced at http://srv1.almuramc.com:8080/player/liache
![image](https://cloud.githubusercontent.com/assets/7806504/21944274/247fca86-d98a-11e6-8e85-390692ff6822.png)
I guess the issue is caused by too long item names from buildcraft pipes.

**Comment by mcsnetworks** [comment]
Do you know if they ever updated this?

**Comment by liach** [comment]
Seems that inquisitor is dead.

**Comment by liach** [comment]
Inquisitor is open sourced on google code archive though.

**Comment by mcsnetworks** [comment]
I don't have the time nor knowledge to fix this.
