### ISSUE TITLE
Inquisitor inventory display issue

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#322]
My status in the game:
![2017-01-13_15 56 49](https://cloud.githubusercontent.com/assets/7806504/21949782/dc5354c4-d9a9-11e6-80d6-c14706325430.png)

my status on Inquisitor:
![image](https://cloud.githubusercontent.com/assets/7806504/21949793/f16e839c-d9a9-11e6-97ea-707d4f539fb8.png)

The inventories are different, as Inquisitor does not properly show modded items. It just says "empty" if you move your mouse onto the slots.

**Comment by mcsnetworks** [comment]
I can't fix this.
