### ISSUE TITLE
Recipe not working

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#323]
Black Pepper recipe is not working.  Attemped by at least 2 people, in several different layouts on crafting tables.  Including the original.

**Comment by deadoss** [comment]
This recipe works as intended. you need to use 16 jars for it to work.
If you would prefer i can change it to produce a single item and use a single jar.

**Comment by Wolfeyeamd0** [comment]
Nope that's fine!  We'll need to make up a list sometime though of these
type of recipes.
