### ISSUE TITLE
Almura 3.0 - Recipe conflict

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/Almura#324]
The Almura Storage Crates are not able to be created due to a conflict with sharing a recipe with  Cabinet 6384 from MrCrayfish's Furniture Mod.

Mod item - CFM_ITEMCABINET - 6384:0

**Comment by Dockter** [comment]
This issue will still be an issue under Almura 3.0

**Comment by Dockter** [comment]
Not an issue any longer.
