### ISSUE TITLE
Suggestion: Crop regrowth

### ISSUE THREAD

**Issue by LordKhaos** [AlmuraDev/Almura#325]
I didn't see a place for suggestions so here we go. I think it would be pretty neat for some of the custom crops to regrow after harvest. Especially with crops that have multiple yields like Grapes. Perhaps make them revert back to a previous growth stage? BTW you're doing great Doc, the effort you guys put into this is amazing.

**Comment by mcsnetworks** [comment]
Closing this as its on our master to-do list.

**Comment by liach** [comment]
Will this be similar to pam's harvestcraft's feature?
