### ISSUE TITLE
Crafting stacks does not reward right exp/money

### ISSUE THREAD

**Issue by LordKhaos** [AlmuraDev/Almura#326]
I was crafting grape juice and red table wine and when I did Shift + Left Click to craft the whole stack, it only gave me exp and money for 1 crafted item. This was for the cooking job, not sure if it's the same for crafter, ect, but I'm sure it's the same for others. Also did this on a vanilla crafting table.

**Comment by Dockter** [comment]
This is likely a weird issue with how Cauldron event tracks specific crafting.  We should test this again once under the full sponge environment.
