### ISSUE TITLE
Suggestion: IC2 compatibility for crops

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#327]
~~Since IC2 is made by Germans, farming enthusiasts, it has a lot of stuff related to farming, integrated to the industrial machines.~~ In the IC2 API, there is a package of `ic2.api.crops` that contains crop related stuff. IC2 crops are custom tile entities; they have very cool features, regarding air quality, weed, and the use of insecticides. It supports crop regrowth as suggested in #325.

**Comment by mcsnetworks** [comment]
I have no intention of making all of Almura's crops into TE's.  The fact that IC2 does this is insane.  I can't imagine having 250,000 TE's ticking in a field.

**Comment by liach** [comment]
I mean just to add cropcards through its api (you can load from existing configurations, I think) I don't think ic2 crops tick in 1.8+, they can just update from block random updates. We may ask @sfPlayer1 for a definite answer.

**Comment by sfPlayer1** [comment]
They tick every 256 server ticks with a random offset. Huge quantities are very unusual since the yield and maintenance effort are quite high.

**Comment by mcsnetworks** [comment]
This is contrary to how Almura's crop system works.  I've had millions planted.
