### ISSUE TITLE
Suggestion: Stackable Water Bottles

### ISSUE THREAD

**Issue by LordKhaos** [AlmuraDev/Almura#328]
I was making rum today and I thought that maybe it would be great if Water Bottles stacked. Non-stackable bottles make mass production rather tedious.

**Comment by mcsnetworks** [comment]
I need to know what item your talking about.  Do an /itemdb with it in your hand and report back your findings.

**Comment by deadoss** [comment]
The item is  POTION  373:0

**Comment by Dockter** [comment]
Added to Almura 3.0 - Release 3 to-do list.
