### ISSUE TITLE
Adds for Builder and Eradicator

### ISSUE THREAD

**Issue by MoraglarKhilen** [AlmuraDev/Almura#329]
Alabaster Bricks (613:0) and its variants stairs(622), slope(618) etc do not provide exp or money
I believe its affecting that entire mod pack(?) I confirmed Doku Stone (599) and bricks (589) also do not give exp or money for placement or destruction as well 

thanks
Moraglar Khilen

**Comment by Dockter** [comment]
Closing since this system will be different in Almura 3.0
