### ISSUE TITLE
Suggestion: New jobs

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#330]
Industrialist: Work with IC2, Railcraft, Buildcraft machines (tech mods)
Trackman: Several railroad related stuff for Railcraft
Tinkerer: Making tools from Tic and use Tic stuff

These ideas may be not implemented till the 1.10 update since the update is very soon and needs much code change.

**Comment by liach** [comment]
I would be interested in contributing once you've decided the job plugin. It will be easier to work with Sponge than Bukkit.

**Comment by Dockter** [comment]
Will re-visit this after Release 2.
