### ISSUE TITLE
[Mod Suggestion] Forestry

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#332]
I suggest Forestry mod for Almura server. This mod is interesting for its addition on trees, bees, mails, and many more features. Forestry is actively maintained; it is also compatible with Buildcraft, Railcraft, and Industrial craft 2.

https://github.com/ForestryMC/ForestryMC
https://forestryforminecraft.info/

**Comment by mcsnetworks** [comment]
Would create too many conflicts at this point.

**Comment by liach** [comment]
Conflicts? Do you mean trees or only add after upgrading to 1.11?
