### ISSUE TITLE
[Mod Suggestion]Chisels and Bits

### ISSUE THREAD

**Issue by Generalcamo** [AlmuraDev/Almura#333]
https://minecraft.curseforge.com/projects/chisels-bits
https://algorithmx2.github.io/Chisels-and-Bits/

Probably the end all for cosmetics, this project includes a configurable and flexible Chisel that can break blocks bit by bit. These bits can be placed in the world for highly customization decorations and similar. The server impact is minimal; I've been running this in a private server for a while with friends who use this extensively, and there is no lag noted. Other servers that use this mod (including ForgeCraft) have reported the same.

It also supports Forge Multipart, which is good news for those who prefer to hide their (Forge MP compatible) wiring.

**Comment by mcsnetworks** [comment]
Will keep it in mind for when we move to Sponge.
