### ISSUE TITLE
Item Duplication Bug

### ISSUE THREAD

**Issue by MoraglarKhilen** [AlmuraDev/Almura#335]
Liquid Heat Generator with BC piping lava into it. Stirling Heat Generator next to it for making EU.
Stack of 64 Empty Universal Fluid Cells put into liquid heat generator to collect the pahoehoe lava. Then do not stay in chunk ( I think definitely cant watch it in interface or check on it all the time must start and let sit ) when you return to take out stack of filled Cells and set of cells also filled with pahoehoe lava appear in the area of the interface for adding normal lava.

**Comment by Dockter** [comment]
Will have to address if still an issue under 3.0
