### ISSUE TITLE
About the rename policy of the server

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#355]
Renames have been supported since mc 1.8, but Almura is in 1.7.10. What does the server do for renamed users?

**Comment by mcsnetworks** [comment]
Shit breaks....

**Comment by liach** [comment]
Sorry, but I don't understand it very well.

**Comment by mcsnetworks** [comment]
What part don't you understand, Residence freaks out, the economy doesn't transfer, it was never written for name changes.

**Comment by mcsnetworks** [comment]
Lets not forget essentials in this....

**Comment by liach** [comment]
Anyways, it is actually good to start as a new player.
