### ISSUE TITLE
Almura 3.0 - HUD Changes

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#361]
Known Issues:
- [x] Name display doesn't display nickname.
- [x] Make numbers within Graphical bars toggle / options in configuration. 
- [x] Debug menu needs to show Minecraft 1.12.1, and Forge (build # Only) on 2nd line.
- [x] Add Commas to Chunk (15,7,13 in 1,4,2)
- [x] Biome display should adapt to what TerrainControl is feeding server.
- [x] Please add temperature and moisture to Biome in debug.
- [x] Add commas to Look: (32, 70, 40)
- [x] Need a way to send modified world name to HUD, example world = "Dakara", not world.  asgard = "Asgard".
- [x] Add "System notification area" for text just below compass that would render outside of the box for server messages like "Server shutting down in 10 minutes" etc.  
- [x] Spacing between server count isn't big enough.
- [x] Add GUI Scaling feature, don't hard-lock to GUI scale within Minecraft.
- [x] Need to edit server list to reflect new Almura 3.0 live/test server environments.
- [x] Add entity target health and stamina meter below worldname/compasss widget that disappears from your screen if your no longer a target OR certain distance away.

**Comment by kashike** [comment]
I'll be working on the nickname feature next.

**Comment by mcsnetworks** [comment]
Added entity target request to this list.

**Comment by Grinch** [comment]
@mcsnetworks Note that I started that in feature/UIEntity but hadn't finished it. Not quite what you're expecting though as I was going more in-depth with it.

**Comment by mcsnetworks** [comment]
Remember MMOTarget?

**Comment by Dockter** [comment]
Instead of adding a healthbar to the players screen I've added it to each entity in the game.

**Comment by Zidane** [comment]
As of the PR for client biome information, rainfall was added to GUI and this issue can now be closed.
