### ISSUE TITLE
Almura 3.0 - Graphics

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#362]
Todo:
* Need a new Almura (Linebelow)Resurrected logo image for Solder / TechnicPack
* Need a new Almura (Linebelow)Resurrected logo image for In-Game MainMenu.
* Need to edit new Almura x128 texture pack, use vanilla background for inventory.png, specifically the blue box image.

**Comment by Grinch** [comment]
Pretty sure it's "Almura Origins". :p

**Comment by Zidane** [comment]
No cause some dumbass used that name for 2.5. Need a new name for 3..

**Comment by Grinch** [comment]
Almura Remastered? Works for most big games lol

**Comment by kashike** [comment]
![x](https://i.vimeocdn.com/portrait/6290775_300x300)

**Comment by mcsnetworks** [comment]
This has been completed.
