### ISSUE TITLE
Almura 3.0 - Server listing screen doesn't auto-refresh, refresh button doesn't work

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#363]
* The server listing screen doesn't auto update.
* Refresh button does nothing.

**Comment by Grinch** [comment]
Unless I'm missing something I don't believe this is a fault of our code: https://github.com/AlmuraDev/Almura/blob/bleeding/src/main/java/com/almuradev/almura/asm/mixin/core/client/gui/MixinGuiMultiplayer.java

Can you verify the issue isn't in Forge, or is in just Almura/MalisisCore without any other mods?

**Comment by mcsnetworks** [comment]
Makes an argument for doing our own server screen.  I prefer 2.5's appearance to vanilla.  Almura != vanilla, that ship sailed a long time ago.

**Comment by Grinch** [comment]
Almura make not be Vanilla, but it's still Minecraft at its heart. We can try and fight it all we want but at the end of the day that will never change. 😛 

At this time I really have no desire to rewrite the screen. If the refresh button doesn't work then we'll need to figure out why and either submit a ticket or make a PR to fix it with the appropriate people (assuming it isn't us at fault).

**Comment by Dockter** [comment]
This won't be an issue once the newer / older server screen gets re-implemented in Almura 3.0.  I'm sorry but Mojang could do so much better on this GUI but chose not to.  Almura 2.5's is better.
