### ISSUE TITLE
Almura 3.0 - Player Details shows unneccessary decimal spots

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#364]
The Player information pane shows health 20.0/20.0.

If a value is an even 20 then we should display 20, not 20.0  All of the redundant zero's seems pointless.

**Comment by Grinch** [comment]
This shouldn't be a difficult fix. Though to be clear here. I'll make it so 20.0 shows as 20 and 19.9 still shows as 19.9.

**Comment by mcsnetworks** [comment]
Correct.  Please add an option to the Almura configuration menu to hide the numbers all together.

**Comment by Dockter** [comment]
This has been fixed in this commit:  https://github.com/AlmuraDev/Almura/commit/1618820da7c8e3f3b76855573fc1bcdc14b49b7d
