### ISSUE TITLE
Almura 3.0 / Grief Prevention Enhancement

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#367]
Since an API exists for GP, it would be neat to hook to it and present the player with a fake world border (renderer effect) to show the parameter of a claim.

**Comment by Dieheart3** [comment]
Maybe with toggles for your own, visit-able ones, ones you cannot enter, and ones that will teleport you to world spawn if you try to enter? (Assuming you don't get rid of the last one because it is super annoying.)

**Comment by Grinch** [comment]
I feel randomly shooting a player from XYZ to the world spawn would just make them rage quit depending on how far they are away. Even with toggles. Just seems odd in my opinion.

**Comment by Dieheart3** [comment]
Yes it does, but I want to be able to at least see the ones that will do it. Because that was(is?) A option you can turn on for your claim... Don't know why but it is.

**Comment by liach** [comment]
use /res unstuck in bukkit

**Comment by Dockter** [comment]
Closing this since this is possible by using the LiteLoader addon for WorldEdit.
