### ISSUE TITLE
Almura 3.0 - client log spam after logoff

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#368]
Error:

https://gist.github.com/mcsnetworks/6fbd657a4b6c120498211acee8e80e5e

Question:  why is a server-side method firing locally?

**Comment by kashike** [comment]
That's not a server-side method, that's a client-side method.

**Comment by mcsnetworks** [comment]
This was being caused by TerrainControl.  Zidane has since fixed the original cause.
