### ISSUE TITLE
Almura 3.0 - SpongeForge server issues

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#376]
The following are issue that exist within SpongeForge that are currently creating issues on Almura:

- Chunks within spawn radius of each world are not unloading
- IC2 TileEntities are being destroyed if a blockBreak action is prevented.
- View Distance is not configurable.

**Comment by Dieheart3** [comment]
Chunks within spawn radius of each world are not unloading, is a base Minecraft issue that you might or might not be able to fix. It is just how they have the game coded. That was added in 1.8 for command blocks that need a loaded chunk to run.

**Comment by Dockter** [comment]
We have already a working prototype where we return .f. in the world.isSpawnChunk method.

**Comment by Dockter** [comment]
This ticket is awaiting the approval of the "keep-loaded" branch within SpongeForge.

**Comment by Dockter** [comment]
Moved this to Almura 3.0 - Release 1 issue.
