### ISSUE TITLE
Almura 3.0 - Add player notification area to GUI & Packet

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#377]
So an idea I've been kicking around.
We need to add a notification area to the users screen, in the center below the world name/compass.

It would be ideal if it could be a popup window that interrupts the player that they need to click OK to or a YES / NO response.

This area is displayed when the client receives a packet from the server.  The packet will include:

- message (string) [Including formatting for color, bold etc]
- notification length (int) [How long to leave on the players screen]
- notification type (int) 0 = GUI, 1 = Popup Window.
- send response?

**Comment by Grinch** [comment]
We already have a [messagebox component](https://github.com/AlmuraDev/Almura/blob/bleeding/src/main/java/com/almuradev/shared/client/ui/component/dialog/UIMessageBox.java). You'd just have to send a packet whenever a result happens.

What kind of information are you looking to display? Be careful with just blindly interrupting a player unless you want people to ragequit when they're asked if they're enjoying the server which interrupts combat with another player or creeper.

**Comment by Dockter** [comment]
Well the player interrupted issue would be resolved with the targeting aspect talked about in another issue.  If they have a monster targeted, delay the message?

**Comment by Grinch** [comment]
Which issue was this discussed in?

How would it be handled? PlayerX attacks EntityY, PlayerX is flagged as inCombat, PlayerX kills EntityY and is flagged as !inCombat, or PlayerX hasn't attacked EntityY in X seconds and is flagged as !inCombat?

**Comment by Dockter** [comment]
Yes, more or less.  It would be the same setup we had in mmoMinecraft, specifically mmoTarget.  The repo's are still up.

**Comment by Dockter** [comment]
This is more or less finished.
