### ISSUE TITLE
Sponge - Dimension / Nether portal issue

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#385]
Performed the following test:

Placed Nether portal within Cemeria @ 0/90/0, went through it to the Nether.  Turned around and returned but I ended up in Dakara (default world).

**Comment by Dockter** [comment]
@Zidane update on this?

**Comment by Zidane** [comment]
Closing as Sponge gained the ability to handle where you're pointing to with teleporter agents.
