### ISSUE TITLE
Create public method to call hasPermission at client

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#386]
We need to create a hasPermissions method within Almura that sends a packet to the server to check for permissions and waits for its response.

**Comment by liach** [comment]
Is it based on mumfrey's clientpermissionlib?

**Comment by Zidane** [comment]
This isn't practical and can easily be solved by sending serialized JsonObject-like data to the client specifying who can do what. Synchronizing permissions was a bad idea back in legacy and is a bad idea today (and really was quite finicky). I'll show an example of this when I help Grinch restore Guide to working state.
