### ISSUE TITLE
Re-Implement Ore Generator

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#391]
Almura 3.0 needs its [PackGenerator] re-implemented.

Previous Class:  
-  https://github.com/AlmuraDev/Almura/blob/master/src/main/java/com/almuradev/almura/pack/generator/PackGenerator.java

Previous CommonProxy Load Entry: 
-  GameRegistry.registerWorldGenerator(new PackGenerator(), 10);

Blocks that need to be included:  
-  https://github.com/AlmuraDev/Resources/blob/master/3.0/fs/assets/almura/content/block/horizontal/ore/marbleore.json
-  https://github.com/AlmuraDev/Resources/blob/master/3.0/fs/assets/almura/content/block/horizontal/ore/saltore.json

Thoughts:  could we include a configuration option and a weighting scale in the json configuration file ore ores?

**Comment by kashike** [comment]
https://github.com/AlmuraDev/Almura/commit/2ce44c9cc446ef184d8515f6bdec4d03c8edc01e
