### ISSUE TITLE
Re-Implement return items during CraftingEvents

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#392]
The following method was added to 1.7.10 that would create additional item stacks to return items such as glass cruets and glass jars in the event an ingredient was used for a crafting recipe.

-  https://github.com/AlmuraDev/Almura/blob/master/src/main/java/com/almuradev/almura/CommonProxy.java#L765

**Comment by liach** [comment]
@Dockter Can we just edit the content item to define its container item stack?

**Comment by Dockter** [comment]
This has been completed.
