### ISSUE TITLE
Re-Implement buckets stacking to 64

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#395]
Almura 1.7.10 had a Mixin that changed the default stacksize of Vanilla buckets:

-  https://github.com/AlmuraDev/Almura/commit/1e02db29e3b6f5532fbdac14de824f47d9aad89b

**Comment by liach** [comment]
Some mods have buckets, too. Do we change their stack sizes?

**Comment by Dockter** [comment]
Completed.
