### ISSUE TITLE
Server Todo:  Shop broken list

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#40]
Below is a running list of known shops that are broken:

1. DocksArea, main shop
2. DocksArea, IronWerks
3. DocksArea, NetherShop
4. Spawn, Sign Shop
5. Spawn, Cafe
6. Spawn, Inn
7. Spawn, Seed Shop
8. Spawn, Grociery Store
9. Spawn, Wolfeye Wool Shop
10. Spawn, Bank
11. Spawn, Tree/Shrub Shop area
11. Foxville Armor & DockArmor shops

**Comment by Grinch** [comment]
Status update @mcsnetworks?

**Comment by mcsnetworks** [comment]
Closing this as most are or are being fixed with b100 content release.
