### ISSUE TITLE
Server Todo: List of broken stargates

### ISSUE THREAD

**Issue by mcsnetworks** [AlmuraDev/Almura#41]
This is a running list of broken stargate locations:

1. Spawn, CityGates
2. Spawn, Player Cities
3. Spawn, Nether Gate
4. DocksArea, (all)
5. Foxville, (main)

**Comment by Grinch** [comment]
Status update @mcsnetworks?

**Comment by mcsnetworks** [comment]
This list is about to get a lot bigger... Hows that for a response?

**Comment by phase** [comment]
@mcsnetworks Could be better.

**Comment by mcsnetworks** [comment]
We are fixing.  This list will both grow and shrink with b100.  The above list is very much out of date.
