### ISSUE TITLE
Opening a UIForm from in-game causes the mouse to disappear until you leave the MC screen

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#412]
Very odd and annoying bug.  Simply open guide, the mouse cursor disappears.

**Comment by Dockter** [comment]
Duct tape fix applied.

**Comment by Grinch** [comment]
Keep this open until we find a way to properly fix it or work with @Ordinastie to address it if it isn't an issue in our own code.

**Comment by Grinch** [comment]
As an update, this isn't limited to the guide screen. The Almanac (both original and my rewrite) were affected by this issue as well.
