### ISSUE TITLE
Guide -> Server Context Window -> Terrible Size, invalid title

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#413]
The window currently labeled "Hurray!" needs a better title.

This window is also too large, should auto-width & auto-height.  OK button is 3 x too large.  Same bug with main GUI window and the {x} remaining to appear highlighted affects this window too.

**Comment by Grinch** [comment]
First part has been addressed in a11bdb3.

**Comment by Dockter** [comment]
Fixed.
