### ISSUE TITLE
Guide -> {?} -> Window side too small, cutting off Guide Title

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#416]
The window the appear is cutting off the guide title, window too small, doesn't auto-size.

**Comment by Grinch** [comment]
This window won't autosize. The title needs to do something like "This is a really long titl...". I can make it wider but to an extent that just seems pointless when you consider that 90% of the details on the screen won't take up more than the space currently allotted.

**Comment by Dockter** [comment]
Fixed,  not using auto-save at the moment.
