### ISSUE TITLE
Guide - Feature Request - > Tickable Parsing of Formatted Text

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#420]
Add an ability to have it auto-format the text one every 5 ticks.  This way when the user is inputting color codes the they won't need to toggle between formatted and raw to see the color/change.

**Comment by Grinch** [comment]
I'm not sure this is something we want to do. Unless you're going to have the § character on-hand to paste for formatting I don't see much benefit.

**Comment by Zidane** [comment]
Unless Ordinastie has made a lot of changes to how that box works, your cursor will be thrown out of whack each time this happens. It would be VERY annoying to edit a page with that happening.

**Comment by Dockter** [comment]
I implemented this.
