### ISSUE TITLE
Mixin itemfood to make them all edible when player's food value is full

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#424]
So that when players combat, it is faster for them to recover.

Right now, A player needs to wait a few seconds for the hunger to drop from 20 to 17. During this time, the player does not get healed.

**Comment by Dockter** [comment]
Whether or not they can eat it while full is a configuration value on the foodItem itself.

**Comment by Zidane** [comment]
As @Dockter said, this is already configurable....

**Comment by liach** [comment]
I mean vanilla ones..
