### ISSUE TITLE
add default destory actions to blocks so that they drop themselves

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#425]

**Comment by Zidane** [comment]
I completely disagree because it makes it almost impossible for the content loader to know when we actually do NOT want to drop anything on break. This is a problem easily fixed by correcting the resource files.

**Comment by Dockter** [comment]
I agree with Zidane on this.

**Comment by liach** [comment]
If the content loader allows contents to extend each other, we may define a destroy action in one of the shared super content jsons instead. Does it do that currently?

**Comment by Dockter** [comment]
It can't do that currently and I'm pretty sure there is no plans to make that possible.
