### ISSUE TITLE
Eating custom food that adds stamina when you have more stamina sets instead of increases you stamina

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#426]
Steps of reproduction:
- Spawn yourself so you have a lot of stamina
- Eat a sunflower seed that says to add 1 stamina in the tooltip
- Observe, in Almura UI, that your stamina becomes 1 (it actually decreases)

I reproduced this with full food value. Don't know if the food value affects the results.

**Comment by Dockter** [comment]
OK, I thought I was nuts when I seen this the first time, apparently not.

**Comment by Dockter** [comment]
@Kashike need your input on this.

**Comment by liach** [comment]
should be an easy fix if we find the spot.
