### ISSUE TITLE
Almura eats stackable buckets

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#427]
Steps to reproduce:
1. Get an item stack of two water buckets.
2. Switch to survival mode.
3. Right click the stack of two water buckets to place down a water source.
4. The expected and actual results differ.

- Expected: The water bucket item in my inventory will decrease size by one, and I will obtain an empty bucket item stack.
- Actual: The water bucket item in my inventory becomes an empty bucket item.

This way, I lose a water bucket.

**Comment by Dockter** [comment]
I believe I have a fix for this coming in b31.

**Comment by Dockter** [comment]
This specific bug is fixed but there are still issues with using stacked buckets in furnaces etc.
