### ISSUE TITLE
Grand Exchange - Functionality explained

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#432]
Picture 1:  http://www.almuramc.com/images/exchange1.png
Model: http://www.eq2interface.com/downloads/full5826.jpg

The slots shown in the picture will be unlocked by the player, 1 slot will be available initially to each player.  The slot represent a storage item such as a Chest.  An chest type item will be dragged into the slots.  The available slots will represent the space available to the player.  If the player clicks on the slot a window will show up similar to how Backpack did.  User can drag items to and from this window.

The list below the slots will be drawn based on which ever slot is selected.  The list will be drawn to show combined items per type and show an itemStack (drawn UIImage) to show the total quantity, 512 if that is what the math works out to be.

Each item can be "Listed for Sale".  If you click on an item in the list and then the button "Set Price" a new window will appear that will allow them to set the price for the selected group of items.

The remove button will remove a single stack of the item selected and place it back into the player inventory (window opening up the child inventory window).

The Pane on the left will be composed of items listed for sale for all players (or based on Item Name or Seller name search fields).  The below list will show items based on type, seller and damage.  Ideally it will only show Cobblestone ONCE for a seller, showing 512 quantity, don't list it multiple times if its from the same seller).

Buttons:  buy stack, buy 1 should be self explanatory. Buy quantity will show a secondary window giving the user the ability to specify MAX or a manual input quantity.

Buttons:  first / previous / next / last will be based on pages since this list on the left should only contain enough items to fill the list once or twice (some scrolling).  This would be necessary so that the SQL calls to the DB aren't too long and lag out the server and client.

Admin ability:  not sure how to implement this:

We have many hundreds of items that don't have recipes, lots of the decorations for example.  It would be ideal to list these as a "Server store" or something that contains these items that users could purchase from the exchange with no player or inventory limit attached to it.  A static list or something configurable json wise would be ideal.

**Comment by TherayTharow** [comment]
For The Admin Ability you can have linked to something like the guide with a lot of setting or a guide
page that you can customize it with § for it to work

**Comment by Zidane** [comment]
Closing this as we don't need this ticket anymore.
