### ISSUE TITLE
TinkersConstruct -> Sponge issue?

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#434]
https://gist.github.com/Dockter/c8144d57881f1e92c22fe77614cffa01

**Comment by Dockter** [comment]
Something to do with Slime Boots, making you bounce instead of taking damage.

**Comment by liach** [comment]
Relevant place of calling packet sending: https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/gadgets/item/ItemSlimeBoots.java#L161

May need mixin output for details.

**Comment by liach** [comment]
Wait @Dockter this is exactly https://github.com/SlimeKnights/TinkersConstruct/issues/3334

**Comment by liach** [comment]
Just update tcon and things will be fine.

**Comment by Dockter** [comment]
Fixed.
