### ISSUE TITLE
Saplings

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#435]
since the last update tree sapling drops have gone down to virtualy 0, i tried all tree types up to now same result even the tinkers slime tree and ic2 rubber tree

**Comment by liach** [comment]
Should be a sponge bleeding bug.

**Comment by Dieheart3** [comment]
I can also say from testing, this affects all blocks that you don't break by hand/tool. Decaying leaves, falling sand/gravel, torches on a block that is falling, mine-carts/boats that break on impact. They will all not want to drop their respective items, only sometimes for some but all the time for most.

**Comment by liach** [comment]
Already fixed. (by updating sponge forge)
