### ISSUE TITLE
LookingDebugPanel doesn't handle name placement correctly when no egg is present

### ISSUE THREAD

**Issue by Grinch** [AlmuraDev/Almura#438]
Some entities may not have eggs and in this case our name placement goes to hell. If there isn't an egg we shouldn't shove the name to the right of where the egg would be. The Y of the name needs to be adjusted as well, as without an egg we draw into the panel above it for the name.

**Comment by liach** [comment]
i think only living entities have eggs. here forge made an extremely bad assumption by binding eggs into entity entries in the registry.

**Comment by Grinch** [comment]
Resolved in b6f5dbdf
