### ISSUE TITLE
LDP's location is wrong.

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#439]
![2018-02-27_19 17 01](https://user-images.githubusercontent.com/7806504/36769271-256c1dbc-1bf8-11e8-920e-4e3a4d1bbfa0.png)

**Comment by Dockter** [comment]
@Grinch I'm at a loss on how to fix this.  I've tried twice.

**Comment by liach** [comment]
Isn't it obvious that this offset is caused by 1e892b4647bd9a68a88c156b14b05acdb58a8c2c?

**Comment by Grinch** [comment]
Resolved with 5ac3f58
