### ISSUE TITLE
Planting Crops, client render stutter

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#441]
When you are walking in a straight line and planting custom crops I am noticing that the client is stuttering, FPS wise.  Stop planting and the issue goes away.

Mesh issue?

**Comment by Zidane** [comment]
You're experiencing remeshing of a chunk. The OBJ baked model caches quads so this is only done once, this is more an issue of the client's renderer than anything else. I'd chase Optifine on this front.
