### ISSUE TITLE
Add soft-dependencies to Almura 3.0

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#442]
I would like to create some companion addon items for SGCraft.  Could someone please make almura 3.0 depend on this:  
* Repo: https://github.com/AlmuraDev/SGCraft/commits/Sponge-7.1.0

I would also like to be able to call upon "UCJDA.sendRawToDiscord" to send message from Almura directly to the discord server.  
* Repo: https://github.com/FabioZumbi12/UltimateChat/tree/master/UltimateChat-Sponge-56

**Comment by Zidane** [comment]
Why not add the companion items straight to SGCraft?

**Comment by Dockter** [comment]
Because I want to also use MalisisCore for the GUI.

**Comment by Dockter** [comment]
Added MalisisCore to SGCraft branch I am using with Sponge.
