### ISSUE TITLE
TC - Biome Feature doesn't seem to be reading colors from configs correctly

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#461]
Example:

Biome: Lakes & Lakeshores;  both have the setting: GrassColor: #FFFFFF but only Lakes seems to show the grass as white.

Please advise.

Water colors also don't appear to be applying either.

**Comment by Zidane** [comment]
I don't read the specific color from the config yet, its purely using temperature + rainfall (what Vanilla actually does). I plan to eventually make it truly use the value in the files but wasn't a priority to do so just yet.

**Comment by Dockter** [comment]
Added to: https://github.com/AlmuraDev/Almura/issues/470

**Comment by Dockter** [comment]
This really cannot be fixed; Optifine is overriding this.
