### ISSUE TITLE
Bucket Quantity Issue with Forge

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#463]
A user has found this problem.

**Issue**: clicking on a tinkers construct seared tank with a lava bucket with a quantity > 1 when the tank is full will result in the tank eating 1 bucker of lava, stack de-increments.  If quantity==1 then the issue does not occur.  

**Code**: Possible code issue is I believe in Forge specifically with " public static IFluidHandlerItem getFluidHandler(@Nonnull ItemStack itemStack)"

TinkersConstruct onBlockActivated Code:  https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/smeltery/block/BlockTank.java#L94

Forge Code Link: https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L470  This specifically says the itemStack will be modified, which is what I assume is causing the buckets to be eaten.

Looking for a possible solution to this other than removing the ability to stack buckets.

**Comment by Dockter** [comment]
One possible solution would be to create a new Almura bucket based on the forge "Universal Bucket" base item?

**Comment by liach** [comment]
I do not think universal bucket fixes this issue. UB also assumes the stack size is always 1.

**Comment by Dockter** [comment]
Added to Almura 3.0 - 1.5 Issue.
