### ISSUE TITLE
Ghost items on death

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#474]
Hi devs jus to let ya know i getting ghost items on death after i pick my stuff up i have to relog to clear the items off the screen

**Comment by liach** [comment]
report at https://github.com/almuradev/gameserver/issues/new instead

**Comment by Dockter** [comment]
@Zidane @gabizou any thoughts on this issue?  Still happening after todays update to both GP and SF.

**Comment by Dockter** [comment]
I believe this was resolved.
