### ISSUE TITLE
Block Duping

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#476]
had a mo-creature green ogre thing in my claim, aggro`ed it and it proceeded to do its attack/destroy everything animation. As the area was claimed it was not doing any damage but it was duping the tinkers construct clear glass the glass wall i have around my base was not dammaged but i ended up getting about 10 blocks of glass from where it was try to break wall.

**Comment by liach** [comment]
go to gameserver repo instead

**Comment by Dockter** [comment]
This is fixed.
