### ISSUE TITLE
Looking for Dev: Content Loaded Flowers are normal blocks

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#483]
@kashike 

It appears that when the content loader loads flowers from /content/block/horizontal/flower that these are just normal blocks and don't implement BlockFlower.

I ask because some of the methods that normal flower have to follow aren't respected.  Example.  Plant a flower, break the block underneath of it, the flower doesn't pop off its current locations like normal flowers do.

**Comment by Zidane** [comment]
@Dockter Have you tested this to see if this works? Want to close this ticket.

**Comment by Dockter** [comment]
This looks like it was fixed long ago.
