### ISSUE TITLE
Exchange: "no results found for that query"

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#489]
Received this:  
![image](https://user-images.githubusercontent.com/1034770/44612709-17da0380-a7d0-11e8-8866-47512d0ca5a7.png)

How I got there:  
- Opened Exchange (nothing was listed yet).
- Clicked on +/-
- Moved all items from inventory to Exchange
- Clicked "OK", got the above message.

**Comment by Dockter** [comment]
Update: can also reproduce this if I unlist the very last item on the exchange.

**Comment by Zidane** [comment]
Wasn't supposed to harass you as it just slows down finding things exponentially. Removed incurrent code.
