### ISSUE TITLE
Exchange - Buy Quantity and buy Stack should only appear if that function is possible

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#497]
Can't buy a stack if only 1 exists and a stack size = 64.  Can't buy quantity if only one is listed.  Why enable the buttons?

**Comment by Grinch** [comment]
'Buy Stack' == Buy the entirely of it, we could change that to say 'Buy All'

I can see your point if one is listed though. I'll make the change to disable these if the quantity == 1
