### ISSUE TITLE
Ores always rendering with in spectator mode

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#525]
A user brought up a good question that after digging into I don't have an answer to.

When in spectator mode it appears that our ORES always render, which means even if the client isn't needing to rendering these deep in a chunk its still doing it.

I tried several things since these are HORIZONITAL blocks to try and solve the issue, from setting the render type to solid, to setting Block_shape_face to solid, even tried reversing some logic in the HorizontalBlockImpl file to try and get them to hide properly and I couldn't seem to get it to work as intended.

Any ideas?

**Comment by TherayTharow** [comment]
this
![2018-10-08_20 58 05](https://user-images.githubusercontent.com/39970604/46666607-16ed0d80-cb95-11e8-963f-7e77d21e51d1.png)

**Comment by liach** [comment]
are ores opaque?

**Comment by TherayTharow** [comment]
yes the texecher is the block no 
it acts like glass

**Comment by liach** [comment]
i am meant to ask doc not you, uh

**Comment by TherayTharow** [comment]
to the point that if you reskin it to
glass you can't tell the differends

**Comment by liach** [comment]
The exact cause: https://github.com/AlmuraDev/Almura/blob/686562e58bb70306d896573346c6c395fc62cafc/src/main/java/com/almuradev/content/type/block/type/horizontal/HorizontalBlockImpl.java#L139-L141

**Comment by TherayTharow** [comment]
Can you have it to where it can be set 
in side of the file that sets the hardens
(can't think of what it was called)
and when it does not find it set it as true

**Comment by liach** [comment]
Not yet. It needs some time for the hooks exposed to the content system. Wait a bit.

**Comment by PowellA12** [comment]
oh okay i was planing to make it the same as something else that does that in it

**Comment by Dockter** [comment]
@liach I tested this return TRUE for both isOpaqueCube and isFullCube and they still appeared during spectator mode.  Any idea's?

**Comment by Dockter** [comment]
Fixed in https://github.com/AlmuraDev/Almura/commit/c4e0289fd513d56bdbf04c8dc366a9e7e56777c4
