### ISSUE TITLE
Content System Load Order

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/Almura#531]
Blocks that can be made from other almura blocks should always load last
So stairs And slabs and Stair"Slopes" can you add some thing at the top of the content file to load the file last Like `LoadLast: True`  and when that line is not in there load order will be the same

**Comment by Dockter** [comment]
No, thats not how this works.

**Comment by liach** [comment]
A topology-based dependency system shall serve better. SpongeCommon already includes a topological sort utility that we can use in the future.
