### ISSUE TITLE
[Bug] On Death Pop-up for respawn don't show up

### ISSUE THREAD

**Issue by iHaX-MrChrissern** [AlmuraDev/Almura#534]
Whenever I die and wait for pop-up it doesn't show up instead I have to Quit and Re-Join for it to pop up. Is this a known issue/bug? If not that be something to look into :)

Best regards Tito

**Comment by Dockter** [comment]
I'm digging into this.  I assume all you get is a dark grey screen with you being dead correct?

**Comment by Dockter** [comment]
Fixed.

**Comment by iHaX-MrChrissern** [comment]
Fantastic 😃

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Fra: Dockter <notifications@github.com>
Sendt: Sunday, March 29, 2020 3:37:18 AM
Til: AlmuraDev/Almura <Almura@noreply.github.com>
Kopi: LordNeo1 <Chriss86@live.no>; Author <author@noreply.github.com>
Emne: Re: [AlmuraDev/Almura] [Bug] On Death Pop-up for respawn don't show up (#534)


Fixed.
