### ISSUE TITLE
going to bed, I cannot get out.

### ISSUE THREAD

**Issue by Paul-Enigma** [AlmuraDev/Almura#535]
Hi Dock,
When ever I go to bed I cannot get out, I stay in the text  mode and have even tried /home , /spawn , these just take me to the locations but it's like I'm sunk in the ground. The only way to come back is to do suicide or leave game. Please advise.

Thanks,

Paul-Enigma

**Comment by Dockter** [comment]
Pushing fix for this tonight.  Thanks for the ticket.
