### ISSUE TITLE
Cows/Chickens follow the player without any breeding item

### ISSUE THREAD

**Issue by Grinch** [AlmuraDev/Almura#538]
Steps to reproduce

1.) Create and load a Singleplayer world
2.) Find a cow/chicken (this may apply to other standard farm animals)
3.) Observe how they will stalk you

**Comment by Dockter** [comment]
Fixed, hopefully.  This is caused by you running the client without the resources.

**Comment by Grinch** [comment]
This issue still occurs with the latest code changes.

**Comment by Dockter** [comment]
Was fixed, again.
