### ISSUE TITLE
Discovered database

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#69]
I would like to create a small database that stores the time a player crafts / discovers a new item in the world for the first time.

**Comment by mcsnetworks** [comment]
We really need to get this moving.  Having a DB side of Almura is important for not only this but other plugins.  This will enable me to start moving away from the rest of our bukkit plugins.

**Comment by Grinch** [comment]
Is this still required since we now have advancements?

**Comment by mcsnetworks** [comment]
yes, this is still needed as each item on the server that is found would be considered a "Discovery"

**Comment by Dockter** [comment]
Added to Almura 3.0 - Release 4 schedule.
