### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by Matterny** [AlmuraDev/Almura#78]
when you use a tinkers lumber axe to chop down mo creatures trees (the blocks, not the entity) it looks like it works, but the blocks are still there, just ghosts.

**Comment by mcsnetworks** [comment]
This commit to Lumberjack should fix that issue.

I will deploy soon.

https://github.com/mcsnetworks/Lumberjack/commit/b6c62ed58a793f763de9795cbd05823cb99a56ff#diff-541d8880523fea335806181a13d2b30fR37
