### ISSUE TITLE
Tunnel Bore Protection

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#82]
![2015-08-23_11 35 43](https://cloud.githubusercontent.com/assets/7806504/9429612/2badd658-498b-11e5-8054-00bf34e5af53.png)
Tunnel bore and some other carts in Railcraft could break protection. I don't think this could be resolved simply by using some plugins.
Ref: https://github.com/CovertJaguar/Railcraft/issues/280

**Comment by liach** [comment]
Btw ic2 dynamite also breaks protection

**Comment by mcsnetworks** [comment]
Fixed the dynamite issue, waiting on feed back regarding event firing from mod dev.

**Comment by mcsnetworks** [comment]
We've forked Railcraft and added in the ability to block this.

PR: https://github.com/AlmuraDev/Railcraft/commit/244cd9f1cb13df59e4b505a90f0ace1b7ef19290
