### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by gabizou** [AlmuraDev/Almura#85]
Requesting [Applied Energistics 2](http://ae2.ae-mod.info/) as a feature on Almura server.

It has a lot of uses for storage, items, crafting, and just overall a really cool mod.

**Comment by mcsnetworks** [comment]
How does this work with the types of energy we already have, IC2, Buildcraft and Railcraft?

**Comment by gabizou** [comment]
AE2 has a block called the [Energy Acceptor](http://ae2.ae-mod.info/Energy-Acceptor/) that can take in energy from those mods.

**Comment by liach** [comment]
And in AE settings you can change the basic energy unit that AE is using (like ~~MJ~~, RF,EU).

**Comment by mcsnetworks** [comment]
Added ae2 already, morph isn't ready for server.
