### ISSUE TITLE
Arcane Levitators kick for "Flying"

### ISSUE THREAD

**Issue by zdaysavior** [AlmuraDev/Almura#87]
The item in question is in the Thaumcraft Mod. It is an item that is supposed to lift players vertically, allowing for a building to be tall, but not have stairs. Anyhow, a problem has arisen with them that the server kicks a player using them with a message stating that "Flying is not allowed on the server", in which case i'm believing that it assumes the rapid increase in a player's Y value, is that player flying straight up. Since i've not heard any complaints about the Harness from Thaumcraft causing this problem, I assume that whatever detects a player flying, detects the gear on the player, yet with the levitator, it is a solid block on the ground, and not attached/worn by the player.

The /itemdb for the item is THAUMCRAFT_BLOCKLIFTER - 1505:0

While it doesn't cause any major problems, it is a big inconvenience having to log back into the server again and again.

Username: zdaysavior

**Comment by mcsnetworks** [comment]
I cannot fix and here is why:

Thaumcraft uses the servers built in fly for this ability.  Since your not a contributor Essentials comes along and kicks you from the server thinking that your flying, I believe.
