### ISSUE TITLE
Bug TC grout block recipe

### ISSUE THREAD

**Issue by regulator152** [AlmuraDev/Almura#88]
Using the TC block recipe in a crafting station, crafting table will not craft grout using 4 blocks of sand 4 blocks of gravel and one block of clay as said you could by NEI. 

Using the Tc recipe for one clay sand and gravel WILL work however.
user name - regulator152

**Comment by liach** [comment]
A [TinkersConstruct's NEI Compat Plugin] (https://github.com/SlimeKnights/TinkersConstruct/tree/master/src/main/java/tconstruct/plugins/nei) bug maybe?

**Comment by mcsnetworks** [comment]
Did you test this in single player?

**Comment by mcsnetworks** [comment]
Outside the scope of Almuras ability to fix this.  Has fix has to come from TC.
