### ISSUE TITLE
mining laser goes past residence protection

### ISSUE THREAD

**Issue by daemenn** [AlmuraDev/Almura#89]
the mining laser from the ic2 mod when fired can destroy blocks that are in the residence of another player

**Comment by mcsnetworks** [comment]
Why the hell does IC2 have its own event system.   WTF is wrong with Forges.  And if you feel the need to have your own why can't you also call the Forge Event handlers....

**Comment by mcsnetworks** [comment]
Fixed the best I can since they don't fire proper forge events.
