### ISSUE TITLE
Add support for custom sounds 

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#9]
Looking to add the ability for the client to play a custom sound when the player walks on a custom block. This would also apply to if a player eats a custom food.

**Comment by Grinch** [comment]
To clarify this request. Basically you want the ability to specify the step sound for blocks and interact sound for items, or just food?

**Comment by mcsnetworks** [comment]
Any Pack[TYPE] should have this feature.

**Comment by Dieheart3** [comment]
This is supported by the 1.8 resource packs. Easy to do even once you know what to do. It is not supported in 1.7.10 however...

**Comment by mcsnetworks** [comment]
This isn't supported by the resource packs come 1.8 because of the nature of Almura's custom blocks.

**Comment by Dockter** [comment]
This is continued on an Amura 3.0 thread.
