### ISSUE TITLE
Lumberjack plugin does not recognize thermal foundation bronze axe

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#91]
I think this issue might be fixed by forking and changing the plugin code to check the item name.

**Comment by gabizou** [comment]
Lumberjack doesn't recognize a lot of the custom tree blocks either.

**Comment by mcsnetworks** [comment]
I purposely disable Lumberjack against custom rules because it was creating ghost blocks on the server.  I cannot get around this easily.
