### ISSUE TITLE
Runic Shielding not affected by no PVP areas

### ISSUE THREAD

**Issue by zdaysavior** [AlmuraDev/Almura#92]
I have noticed that the items from Thaumcraft that provide Runic Shielding, don't follow an areas "No PVP" rule, and still is affected by being hit. While you still don't get damaged once it runs out, it still provides a fairly large knockback to the person being hit. This could cause some problems in non-PVP res's in which someone wearing the Runic Shielding, gets knocked off a cliff or something similar.

zdaysavior

**Comment by mcsnetworks** [comment]
This is going to be a player based affect that won't throw an event at the server because it isn't damaging the player.

Can't help.
