### ISSUE TITLE
Residence Bucket Permission

### ISSUE THREAD

**Issue by liach** [AlmuraDev/Almura#95]
Allows getting water from residence but prevents placing it.
Screenshot:
![2015-08-27_22 15 53](https://cloud.githubusercontent.com/assets/7806504/9539659/7afd4398-4d09-11e5-9cb9-4d80f118eb88.png)

**Comment by mcsnetworks** [comment]
You didn't state which bucket your using...

**Comment by liach** [comment]
They were two empty buckets at first, then I right clicked those two blocks of water with my buckets. Buckets got filled and I cannot place the water back.

**Comment by mcsnetworks** [comment]
Type /itemdb with the item in your hand.

**Comment by liach** [comment]
Yes it's a water bucket, reproduced it again close to the spawn
![2015-08-28_12 43 10](https://cloud.githubusercontent.com/assets/7806504/9555528/7337beee-4d82-11e5-929b-bdd819685099.png)

**Comment by mcsnetworks** [comment]
This has been fixed.
