### ISSUE TITLE
Anvil Issues

### ISSUE THREAD

**Issue by Matterny** [AlmuraDev/Almura#96]
When anyone puts a specific sword of the zepher in an anvil, there game crashes.

**Comment by Matterny** [comment]
pastebin for crash report: http://pastebin.com/YNTnkBg5
the logs dont fit in a pastebin, they will be in the next post

**Comment by mcsnetworks** [comment]
You didn't post the full item name as I asked for by doing a /itemdb

**Comment by Matterny** [comment]
full item id : THAUMCRAFT_ITEMSWORDELEMENTAL - 5007:0
The item name is "Sword of the Zephyr"
Is this all the required info or am I missing something?

**Comment by liach** [comment]
try without nei

**Comment by mcsnetworks** [comment]
I've seen this issue before where mod dev's don't handle the repair ability correctly.  Nothing on our end we can do to resolve it.  Thaumcraft's source code is closed source.
